supabase/realtime

Dockerfile, Makefile, docker-compose.yml, server/README.md, server/config/releases.exs
@kiwicopple could use your input.
1) Should this be a part of the public repo or is it specific to internal infrastructure?
2) if it's useful for public, where should I put dependency information (needs gcloud cli)
3) <s>also where to put instructions on how to get deploy keys (secrets.json)</s> actually not needed
4) comments on make file addition style welcome
=> added make command to deploy to google run deploy

server/lib/realtime/replication.ex
fixes the issue I was having with creating rooms with null values, @kiwicopple could you just cast an eye just in case
I ran the tests as well and all looks well
=> potential fix for https://github.com/supabase/realtime/issues/21

.github/workflows/ci.yml, .github/workflows/release.yml
Creates a binary artifact under Releases (realtime-ubuntu-latest.tar.gz) when a tag is pushed.
Also uploads a Docker image with the corresponding tag to Docker Hub (requires setting secrets: DOCKER_USERNAME and DOCKER_PASSWORD).
Closes #28. Ticks 2 items off #30.
=> Automate tests, build, & release

.github/workflows/release.yml
=> fix: converts all "set-env" commands. Now dumps to an env file

server/lib/realtime/subscribers_notification.ex
=> fix: sends column subscriptions on delete

.github/workflows/release.yml, .releaserc.json, server/mix.exs
Chore.
Automate release versioning with [semantic-release-replace-plugin](https://github.com/google/semantic-release-replace-plugin).
Closes #93.
=> chore: automate versioning

examples/next-js/README.md, examples/next-js/package-lock.json, examples/next-js/package.json
Next JS example doc update
Focus of this PR is to inform users of running Next JS example in dev mode. Also, updates `examples/next-js/package-lock.json`.
=> Add 'npm run dev' instruction to Next JS example doc

server/lib/adapters/adapter_conn_retry.ex, server/lib/adapters/postgres/epgsql_implementation.ex, server/lib/realtime/application.ex, server/lib/realtime/replication.ex, server/lib/realtime/replication_supervisor.ex, server/test/realtime/replication_test.exs
=> fix: undefined.handle_message errors

server/rel/env.sh.eex
feature
Enable observer in stage/production Elixir releases.
Make sure to include:
export RELEASE_NAME=realtime
export RELEASE_COOKIE=s0m3Pa55word
See https://blog.aplombtech.in/2020/06/07/set-up-remote-elixir-observer-for-mix-release for more information.
=> feat: enable observer in Elixir release

.github/workflows/release.yml
Bug fix.
Update `docker/build-push-action` Action to `v2` to support multi-arch.
=> fix(release): up docker/build-push-action to v2

README.md
docs update
clear instruction on how to pass in JWT for client connection authorization.
=> Add instruction on client passing in JWT as query params

server/lib/realtime/application.ex
Based on https://github.com/epgsql/epgsql#connect , but untested
=> chore: add application_name to differentiate connections on the DB

Dockerfile
This PR updates Elixir to 1.11.4 and fixes the deploy build
=> update Elixir version to 1.11.4 in Dockerfile

server/config/test.exs, server/lib/realtime/application.ex, server/lib/realtime/helpers.ex, server/lib/realtime/message_dispatcher.ex, server/lib/realtime/rls/replication_poller.ex, server/lib/realtime/rls/subscriptions/subscriptions.ex, server/lib/realtime/subscribers_notification.ex, server/lib/realtime/subscription_manager.ex, server/mix.exs, server/test/realtime/message_dispatcher_test.exs, server/test/realtime/replication_poller_test.exs, server/test/realtime/replication_test.exs, server/test/realtime/rls_replications_test.exs, server/test/realtime/rls_subscriptions.ex, server/test/realtime/rls_subscriptions_test.exs, server/test/realtime/subscribers_notification_test.exs, server/test/realtime/subscription_manager_test.exs, server/test/realtime_web/channels/realtime_channel_test.exs, server/test/setup.sql
Bug fix, feature, docs update, ...
Please link any relevant issues here.
=> [WIP] start use db in tests and RLS tests

server/lib/realtime_web/channels/realtime_channel.ex, server/test/realtime_web/channels/realtime_channel_test.exs
Bug fix
Enable Realtime channel join when `user_token` JWT does not contain sub and email data.
This is possible when `supabase-js` attempts to subscribe to a channel and passes in anonymous key to `user_token` (see [ref](https://github.com/supabase/supabase-js/blob/134105f5f6c966f46fe77213a80de3e28e75441f/src/SupabaseClient.ts#L161) and [ref](https://github.com/supabase/supabase-js/blob/52d417c05aa84a9b9c7b769a2c40a6bcd4f07603/src/lib/SupabaseRealtimeClient.ts#L15)).
=> fix: handle realtime channel join when sub and email are absent

server/lib/realtime/rls/replications.ex
Bug fix
`wal2json` `add-tables` behaves differently depending on the Postgres version (tested 12, 13, and 14).
Postgres 12 + 14: if `add-tables` is passed an empty string then no changes are returned
Postgres 13: if `add-tables` is passed an empty string then changes from all tables are returned
publication tables are passed to `add-tables` as long as there's at least one table in the publication.
Related issue: https://github.com/supabase/supabase/issues/4201
=> fix: pass any and all publication tables to wal2json add-tables

server/lib/realtime/rls/subscriptions/subscriptions.ex
Bug fix
filters break when there are colons in the value. for example:
`realtime:public:users:name=eq.w3:b6`
value is preserved when it contains colons
=> fix: filter value is preserved when it contains colon(s)

server/lib/realtime_web/channels/realtime_channel.ex
feature
only the `authenticated` role access token is being checked and updated when client sends it.
all roles' access tokens will be checked and updated.
=> feat: verify token of all roles coming from client

LICENSE
chore
Update license copyright year to 2022.
=> chore: update license copyright year to 2022

LICENSE
This reverts commit 11c639cffcbfa87c3f1a45cc690055fa93b8a149, reversing changes made to 88c6b8cac05d4531fc48c3dba38ea6a004e161d5.
=> Revert "Merge pull request #259 from supabase/chore/update-license"

examples/next-js/package-lock.json, examples/next-js/package.json, examples/next-js/pages/index.js, server/lib/realtime/application.ex, server/lib/realtime/helpers.ex, server/lib/realtime/message_dispatcher.ex, server/lib/realtime/rls/replication_poller.ex, server/lib/realtime/rls/subscriptions/subscriptions.ex, server/lib/realtime/subscription_manager.ex, server/lib/realtime_web/channels/presence.ex, server/lib/realtime_web/channels/realtime_channel.ex, server/test/realtime/message_dispatcher_test.exs, server/test/realtime/rls_subscriptions_test.exs, server/test/realtime/subscription_manager_test.exs, server/test/realtime_web/channels/realtime_channel_test.exs, server/test/support/joken_current_time_mock.ex
feat
RealtimeChannel checks if access token has expired every 60 seconds.
RealtimeChannel sends message to self every 5 minutes or when token is expiring, whichever is less, to verify token.
=> feat: support Broadcast, Presence, and new API

server/lib/realtime/application.ex, server/lib/realtime/helpers.ex, server/lib/realtime/message_dispatcher.ex, server/lib/realtime/rls/replication_poller.ex, server/lib/realtime/rls/subscriptions/subscriptions.ex, server/lib/realtime/subscription_manager.ex, server/lib/realtime_web/channels/presence.ex, server/lib/realtime_web/channels/realtime_channel.ex, server/test/realtime/message_dispatcher_test.exs, server/test/realtime/rls_subscriptions_test.exs, server/test/realtime/subscription_manager_test.exs, server/test/realtime_web/channels/realtime_channel_test.exs
feature
Revert new API and Broadcast and Presence functionalities.
=> feat: remove new API with Broadcast and Presence

.dockerignore, Dockerfile, docker-compose.dev.yml
fixes https://github.com/supabase/cli/pull/540
container cannot be started locally due to missing entrypoint
copy entrypoint into app container
logs from startup
```
realtime-db-1        | PostgreSQL init process complete; ready for start up.
realtime-db-1        |
realtime-db-1        | 2022-10-19 10:12:52.879 UTC [1] LOG:  starting PostgreSQL 14.3 (Debian 14.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
realtime-db-1        | 2022-10-19 10:12:52.879 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
realtime-db-1        | 2022-10-19 10:12:52.880 UTC [1] LOG:  listening on IPv6 address "::", port 5432
realtime-db-1        | 2022-10-19 10:12:52.884 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432" …
```
=> fix: add missing entrypoint to dockerfile

.github/workflows/ci.yml, .github/workflows/release.yml, .releaserc, README.md
Chore
References `master` branch
References `main` branch
=> chore: rename branch master to main

.github/workflows/mt_prod.yml, .github/workflows/mt_prod_linter.yml, .github/workflows/mt_staging.yml, .github/workflows/mt_staging_linter.yml, .github/workflows/mt_staging_supabench.yml, .releaserc
Chore
Add GitHub workflows for Multi-Tenant Realtime
Will need to do some consolidating but this is first steps.
=> chore: add GitHub workflows for Multi-Tenant Realtime

Dockerfile, deploy/fly/prod.toml, deploy/fly/qa.toml, deploy/fly/staging.toml, rel/env.sh.eex
fix
Docker image doesn't work for local dev.
Docker image works for local dev.
=> fix: prepare Docker image for local development

config/prod.exs
This reverts commit 332660e1dd88394b634ce980ae333decc08c9d93.
=> chore: Revert "feat: add LOG_LEVEL env var for prod"

lib/realtime_web/channels/realtime_channel.ex
Bug fix
Phoenix Presence shard can be overwhelmed if many channels of the same topic try to call `Presence.list` at or around the same time. This leads to shard time out errors after 5 seconds which causes the channel to crash.
Channel will check to see if topic is currently tracking any presences by fetching from `ets` table directly. If there are presences then it reverts back to `Presence.list` call b/c only the shard state has access to down replicas.
=> fix: handle Presence list call timeout without crashing channel

lib/extensions/postgres_cdc_rls/replication_poller.ex, lib/extensions/postgres_cdc_stream/replication.ex, lib/realtime.ex, lib/realtime/api/extensions.ex, lib/realtime/gen_counter/dynamic_supervisor.ex, lib/realtime/monitoring/prom_ex_plugins_osmon.ex, lib/realtime/rate_counter/dynamic_supervisor.ex, lib/realtime_web/live/components.ex, test/realtime/postgres_decoder_test.exs
=> chore: moduledocs

.github/workflows/mirror.yml, .github/workflows/prod.yml
See original PR: https://github.com/supabase/realtime/pull/365
=> feat: release docker image to ghcr

lib/realtime_web/endpoint.ex, test/integration/rt_channel_test.exs
=> Feat: enable long polling

Makefile, deploy/fly/prod.toml, deploy/fly/qa.toml, deploy/fly/staging.toml, dev/postgres/00-setup.sql, docker-compose.dbs.yml, docker-compose.yml, lib/realtime/release.ex, priv/repo/seeds.exs
chore
Local Docker setup for multi-tenant Realtime is a breeze.
=> feat: streamline local Docker setup

lib/realtime/helpers.ex, lib/realtime_web/channels/user_socket.ex, lib/realtime_web/plugs/assign_tenant.ex, lib/realtime_web/plugs/rate_limiter.ex, test/realtime/helpers_test.exs, test/realtime_web/plugs/assign_tenant_test.exs, test/realtime_web/plugs/rate_limiter_test.exs, test/test_helper.exs
Fixes and adds tests for plugs to assign a tenant, and rate limit any future API endpoints we may expose to tenants directly.
=> bug: fix tenant api limiter

README.md
Docs update
Updated README for Multi-Tenant Realtime cluster with Broadcast, Presence, and Postgres Changes.
=> chore: update README for v2

README.md
=> fix: Format readme.md

lib/realtime/repo.ex
- Increase the read replica pool size before adding db response caching
=> fix: increase read replica pool size

priv/repo/seeds.exs
feature
Addresses: https://github.com/supabase/realtime/issues/411 and https://github.com/supabase/realtime/issues/415
=> feat: default realtime-dev JWT secret to API_JWT_SECRET env var value

lib/extensions/postgres_cdc_rls/migrations.ex, lib/realtime/repo.ex
Improves `Repo.with_dynamic_repo/2` by defaulting `name` to `nil` and `pool_size` to `1`.
=> feat: default Repo with_dynamic_repo name to nil and pool_size to 1

.github/workflows/mirror.yml, .github/workflows/prod.yml
instead of long lived access keys
=> fix: switch to aws roles

config/runtime.exs
Followup to https://github.com/supabase/realtime/pull/441.
=> fix: load sjc replica from DB_HOST_REPLICA_SJC env var

lib/extensions/postgres_cdc_rls/replication_poller.ex
Bug fix
Replication poller process blocks b/c it's forced to sleep when retrying poller.
Replication poller process sends message to self based on backoff timeout.
Updates rand exp backoff max from 2 minutes to 5 seconds.
=> fix: replace replication poller process sleep with send_after

assets/js/app.js
Bug fix
Addresses: https://github.com/supabase/realtime/pull/450
=> fix: replace inspector latency rounding with fixed two decimal places

lib/realtime_web/live/page_live/index.html.heex
- WebSocket
- "real-time" when describing the feature
=> fix: grammar/spelling changes

lib/realtime/postgres_cdc.ex, lib/realtime/repo.ex
- Move `fra` to `lhr`
- Move `sjc` to `sea`
=> feat: change regions

lib/realtime/helpers.ex, lib/realtime/monitoring/latency.ex, lib/realtime_web/live/status_live/index.ex, lib/realtime_web/live/status_live/index.html.heex
- dropdowns to select `from` and `to` regions
- show seconds from last ping
- color something orage > red depending on latency and maybe seconds from last ping
- dropdown for sort by
=> feat: status page improvements

deploy/fly/staging.toml
- staging only: adds volumes to Fly configs
=> feat: add volume Fly config staging

lib/realtime/api.ex, lib/realtime_web/live/components.ex, lib/realtime_web/live/tenants_live/index.ex, lib/realtime_web/live/tenants_live/index.html.heex
- fixes order by for admin tenants list
=> fix: order by correctly

.github/workflows/prod.yml
This action does the following: 
- moves releases/latest to releases/version
- publishes releases/version to github
- switches to main
- deletes releases/latest
- creates releases/latest
- publishes releases/latest again
=> feat: releases branch action

mix.exs
- should match version in releases list
=> feat: bump to 2.6.0

.github/workflows/prod.yml, deploy/fly/prod.toml, deploy/fly/staging.toml, lib/extensions/postgres/adapters/postgres/decoder/decoder.ex, lib/extensions/postgres/adapters/postgres/decoder/oid_database.ex, lib/realtime/api.ex, lib/realtime/monitoring/prom_ex/plugins/tenant.ex, lib/realtime_web/live/components.ex, lib/realtime_web/live/tenants_live/index.ex, lib/realtime_web/live/tenants_live/index.html.heex, mix.exs
=> release v2.6.0

.github/workflows/prod.yml, .github/workflows/version_updated.yml
- moves version check into its own workflow
=> fix: move mix check

.github/workflows/prod.yml, .github/workflows/prod_linter.yml, .github/workflows/staging.yml, .github/workflows/staging_linter.yml, .github/workflows/staging_supabench.yml
- previously sem release bs would block Fly deploys
- let's always deploy on release
=> feat: deploy always runs on release

lib/extensions/postgres_cdc_rls/migrations.ex, lib/extensions/postgres_cdc_rls/repo/migrations/20230228184745_convert_commit_timestamp_to_utc.ex
feature
commit_timestamp will be converted to utc.
- https://github.com/supabase/walrus/pull/70
=> feat: convert commit_timestamp to utc

lib/extensions/postgres_cdc_rls/replication_poller.ex, lib/realtime/api.ex, lib/realtime/tenants.ex, lib/realtime_web/channels/realtime_channel.ex, lib/realtime_web/plugs/assign_tenant.ex, test/realtime/tenants_test.exs
- Found the spot to start tracking db events, can do this whenever
=> feat: track db events

Dockerfile, test/realtime/extensions/cdc_rls/subscriptions_checker_test.exs
=> fix: upgrade Erlang and Elixir and fix test

lib/realtime_web/channels/realtime_channel.ex, mix.exs
Presence is eventually consistent anyways why run `list` through a GenServer?
=> fix: dirty_list Presence

deploy/fly/prod.toml, deploy/fly/qa.toml, deploy/fly/staging.toml, mix.exs
Need this to write crash dumps
=> fix: set ERL_CRASH_DUMP_SECONDS to 30

Makefile, lib/realtime/monitoring/os_metrics.ex, mix.exs, rel/vm.args.eex
* fix: use available_memory for memory metric on prod
* fix: set max_heap_size for all procs to 1000 mb
* fix: version
=> Release v2.12.6

Makefile, config/config.exs, config/dev.exs, config/runtime.exs, lib/realtime/cluster_strategy/postgres.ex, mix.exs, test/realtime/cluster_strategy/postgres_test.exs
feature
Current cluster strategy is DNS polling.
New cluster strategy is Postgres LISTEN/NOTIFY (pub/sub) via heartbeat mechanism.
=> feat: add Postgres libcluster strategy

.github/workflows/prod.yml, .github/workflows/staging.yml, .github/workflows/staging_supabench.yml, mix.exs
Biggest thing we get remote builds in 1.2
=> fix: upgrade flyctl to 1.4

assets/js/app.js, lib/realtime_web/channels/realtime_channel.ex, mix.exs
- console log Channel errors for Inspector
- log messages from `handle_info` if `log_level` is less than `:error`
=> fix: more debug tools

assets/js/app.js, lib/realtime_web/live/inspector_live/conn_component.ex, lib/realtime_web/live/inspector_live/conn_component.html.heex, mix.exs
Toggle Presence and Database Changes when subscribing from the Inspector:
=> feat: more Inspector opts

mix.exs, tailscale/wrapper.sh
=> fix: Handle unbound variable error

mix.exs, tailscale/wrapper.sh
Set default value on startup command
=> fix: Set default value on startup command

lib/realtime/postgres_cdc.ex, mix.exs
Properly map us-west-2 connections
=> fix: Properly map us-west-2 connections

lib/extensions/postgres_cdc_rls/migrations.ex, mix.exs
Log info about which host ran the migration
=> fix: Log info about which host ran the migration

lib/realtime/user_counter.ex
- adds moduledoc
- don't bump version so it matches release version
=> fix: add module doc

lib/realtime_web/controllers/broadcast_controller.ex, lib/realtime_web/plugs/auth_tenant.ex, mix.exs
Add logging to Broadcast endpoint for better debugging
=> fix: Add logging to Broadcast endpoint for better debugging

lib/realtime/tenants/batch_broadcast.ex, lib/realtime_web/controllers/broadcast_controller.ex, mix.exs, test/realtime_web/controllers/broadcast_controller_test.exs
Current format was not compliant with what was expected by our channel clients
=> fix: Change payload from Broadcast endpoint

lib/realtime/postgres_cdc.ex, mix.exs
Change south-1 to use southeast-1
=> fix: Change south-1 to use southeast-1

mix.exs, test/integration/rt_channel_test.exs, test/realtime/cluster_strategy/postgres_test.exs
Increase timeout in certain tests to reduce flakyness during CI
=> fix: Reduce test flakyness

.github/workflows/prod_build.yml, mix.exs
Fixes https://github.com/supabase/realtime/issues/618
=> fix: Push docker latest versions

lib/extensions/postgres_cdc_rls/subscriptions.ex, mix.exs
More logging details on param parsing
=> fix: More logging details on param parsing

lib/extensions/postgres_cdc_rls/subscriptions.ex, lib/realtime_web/channels/realtime_channel.ex, mix.exs, test/realtime/extensions/cdc_rls/subscriptions_test.exs
Fix old API compatibility and redact tokens
=> fix: Fix old API compatibility

lib/realtime/tenants/connect.ex, mix.exs
Increase interval between checks to 10 seconds
=> fix: Increase interval between checks to 50 seconds

lib/realtime/application.ex
Fix version parity between GH and Docker
=> fix: Fix version parity between GH and Docker

lib/realtime/tenants/migrations.ex, mix.exs
Stop migration process after migrations are done
=> fix: Stop migration process after migrations are done

lib/realtime/helpers.ex, lib/realtime/tenants/connect.ex, mix.exs
Add application name to Connect module
=> fix: Add application name to Connect module

lib/extensions/postgres_cdc_rls/subscription_manager.ex, lib/extensions/postgres_cdc_rls/subscriptions_checker.ex, mix.exs
Add application_names to more connect_db usages
=> fix: Add application_names to more connect_db

config/config.exs, config/dev.exs, config/prod.exs, lib/realtime/helpers.ex, lib/realtime/tenants/connect.ex, mix.exs
Add application_name to Logger context
=> fix: Add application_name to Logger context

lib/realtime/helpers.ex, mix.exs
Add logs to connection killing
=> fix: Add logs to connection killing

lib/realtime/helpers.ex, mix.exs
=> fix: Async connection killing

lib/extensions/postgres_cdc_rls/replication_poller.ex, lib/realtime/helpers.ex, lib/realtime/tenants/connect.ex, mix.exs
* Fixes application name on the connect module to align with other application names
* Fixes logger context on rls connection so we have tenant information on errors
=> fix: Application name fix and Logger context fix

lib/realtime/helpers.ex, mix.exs, test/realtime/tenants/connect_test.exs
Improve readability of conn killer
=> fix: Improve readability of conn killer

lib/realtime/api/channel.ex, lib/realtime/channels.ex, lib/realtime/repo.ex, lib/realtime/tenants/migrations.ex, lib/realtime/tenants/repo/migrations/20231018144023_create_channels.ex, mix.exs, test/realtime/channels_test.exs, test/realtime/extensions/cdc_rls/replication_poller_test.exs, test/realtime/repo_test.exs, test/support/generators.ex
Adds the concept of Channels into the Tenant database
Also adds some helper methods to handle SQL queries and results in a more "Elixir" way
=> fix: Add Channels to Tenants

lib/realtime/api/channel.ex, lib/realtime/channels.ex, lib/realtime/repo.ex, lib/realtime_web/controllers/channels_controller.ex, lib/realtime_web/open_api_schemas.ex, lib/realtime_web/plugs/assign_tenant.ex, lib/realtime_web/router.ex, mix.exs, test/realtime/channels_test.exs, test/realtime/repo_test.exs, test/realtime_web/controllers/channels_controller_test.exs, test/support/conn_case.ex, test/support/data_case.ex, test/support/generators.ex
Adds the listing endpoints and implements more changes to the way we're loading data
=> fix: Add Channels listing endpoint

mix.exs, priv/repo/seeds.exs
Restrict seed file to handle test and dev environments
=> fix: Restrict seed file to handle test and dev environments

mix.exs, priv/repo/seeds.exs, tailscale/wrapper.sh
Handle lack of Mix in production env
=> fix: Handle lack of Mix in production env

lib/realtime/channels.ex, lib/realtime_web/controllers/channels_controller.ex, lib/realtime_web/controllers/fallback_controller.ex, mix.exs, test/realtime/channels_test.exs, test/realtime_web/controllers/channels_controller_test.exs
=> fix: Add Show channel endpoint

lib/realtime/api/channel.ex, lib/realtime/channels.ex, lib/realtime/repo.ex, lib/realtime_web/controllers/channels_controller.ex, lib/realtime_web/open_api_schemas.ex, mix.exs, test/realtime/channels_test.exs, test/realtime/repo_test.exs, test/realtime_web/controllers/channels_controller_test.exs
=> fix: Add create Channel endpoint

lib/realtime/channels.ex, lib/realtime/repo.ex, lib/realtime_web/controllers/channels_controller.ex, mix.exs, test/realtime/channels_test.exs, test/realtime/repo_test.exs, test/realtime_web/controllers/channels_controller_test.exs
Adds delete endpoint along with other delete code required for the feature
To be merged after https://github.com/supabase/realtime/pull/743
=> fix: Add delete endpoint

lib/realtime_web/router.ex, mix.exs, test/realtime/repo_test.exs, test/realtime_web/controllers/channels_controller_test.exs
Remove channels controller temporarily
=> fix: Remove channels controller temporarily

mix.exs, tailscale/wrapper.sh
Handle S3 key in env var and aws request
=> fix: Handle S3 key in env var and aws request

mix.exs, tailscale/wrapper.sh
Fix correct variable used for HTTPS
=> fix: Fix correct variable used for HTTPS

mix.exs
Bug fix, feature, docs update, ...
Please link any relevant issues here.
=> fix: Bump up version

lib/extensions/postgres_cdc_rls/cdc_rls.ex, lib/extensions/postgres_cdc_rls/subscriptions_checker.ex, lib/extensions/postgres_cdc_stream/cdc_stream.ex, lib/realtime/helpers.ex, lib/realtime/monitoring/latency.ex, lib/realtime/monitoring/prom_ex/plugins/tenants.ex, lib/realtime/rpc.ex, lib/realtime/tenants/connect.ex, lib/realtime_web/controllers/metrics_controller.ex, mix.exs
=> fix: Add rpc metrics to promex

lib/realtime/monitoring/prom_ex/plugins/tenants.ex, mix.exs
Change from Sum to Distribution on RPC metrics
=> fix: Change from Sum to Distribution on RPC metrics

lib/extensions/postgres_cdc_rls/cdc_rls.ex, lib/extensions/postgres_cdc_stream/cdc_stream.ex, lib/extensions/postgres_cdc_stream/replication.ex, lib/realtime/postgres_cdc.ex, lib/realtime_web/channels/realtime_channel.ex, lib/realtime_web/controllers/tenant_controller.ex, mix.exs, test/realtime/extensions/cdc_rls/cdc_rls_test.exs, test/realtime_web/controllers/tenant_controller_test.exs
Replication Slot deletion on Tenant delete
=> fix: Replication Slot deletion on Tenant delete

lib/realtime/tenants/connect.ex, mix.exs
Handle invalidate_cache message on Connect
=> fix: Handle invalidate_cache message on Connect

lib/realtime_web/open_api_schemas.ex, mix.exs
Was spec'd as an object, it's actually a string.
=> fix: broadcast POST body spec

lib/realtime/helpers.ex, mix.exs
=> fix: erpc calling wrong function

lib/realtime_web/channels/realtime_channel/broadcast_handler.ex, lib/realtime_web/channels/realtime_channel/presence_handler.ex, mix.exs
Improve logging by adding when messages are ignored
=> fix: Improve logging by adding when messages are ignored

lib/realtime_web/channels/realtime_channel.ex, mix.exs
Missing broadcast condition check on handle_info for messages pushed to the socket.
=> fix: Missing broadcast condition check

lib/realtime_web/channels/realtime_channel.ex, mix.exs
Matching error due to way socket was being used
=> fix: Matching error due to way socket was being used

lib/realtime_web/channels/realtime_channel.ex, mix.exs
Will not push message to socket if no read policy
=> fix: Will not push message to socket if no read policy

lib/realtime/tenants.ex, lib/realtime/tenants/authorization.ex, lib/realtime_web/channels/realtime_channel.ex, mix.exs
Prioritize channel policies; Run migrations on healthcheck
=> fix: Prioritize channel policies; Run migrations on healthcheck

lib/realtime_web/controllers/broadcast_controller.ex, mix.exs
Query different region for channels
=> fix: Query different region for channels

lib/realtime/tenants/repo/migrations/20240401105812_create_realtime_admin_and_move_ownership.ex, mix.exs
Handle supabase_realtime_admin already exists
=> fix: Handle supabase_realtime_admin already exists

lib/extensions/postgres_cdc_rls/cdc_rls.ex, lib/extensions/postgres_cdc_stream/cdc_stream.ex
docs update
Please link any relevant issues here.
=> fix some typos

lib/extensions/postgres/adapters/postgres/decoder/oid_database.ex, lib/extensions/postgres_cdc_rls/cdc_rls.ex, lib/extensions/postgres_cdc_stream/cdc_stream.ex
docs update
Please link any relevant issues here.
=> chore: fix some typos

lib/realtime_web/controllers/broadcast_controller.ex, mix.exs, test/realtime_web/controllers/broadcast_controller_test.exs
Remove policies temporarily to avoid stopping service
=> fix: Remove policies temporarily to avoid stopping service

lib/realtime_web/controllers/broadcast_controller.ex, mix.exs, test/realtime_web/controllers/broadcast_controller_test.exs
There was an bug where channel topics were not properly set on realtime_channel.ex so the issue was not in this code.
=> fix: Revert Broadcast Controller

lib/realtime_web/channels/realtime_channel.ex, mix.exs
Error matching when it's a public channel
=> fix: Error matching when it's a public channel

lib/realtime_web/channels/realtime_channel.ex, mix.exs
=> fix: Public Channel definition

lib/realtime_web/controllers/broadcast_controller.ex, mix.exs
Remove unnecessary checks on DB for Broadcast endpoint
=> fix: Remove unnecessary checks on DB for Broadcast endpoint

lib/realtime_web/controllers/broadcast_controller.ex, mix.exs
Avoid fetching connection if not required
=> fix: Avoid fetching connection if not required

lib/realtime_web/channels/realtime_channel.ex, mix.exs
=> fix: Handle missing error encoding

lib/extensions/postgres_cdc_rls/cdc_rls.ex, lib/realtime/helpers.ex, lib/realtime_web/channels/realtime_channel.ex, mix.exs
Removing an extra log line and also reverting pool changes to be as they were previously ( https://github.com/supabase/realtime/pull/850/files )
=> fix: Remove extra log; Revert pool changes

Dockerfile, docker-compose.yml, limits.sh, mix.exs, tailscale/wrapper.sh
Remove hardcoded limit from container
=> fix: Remove hardcoded limit from container

Dockerfile, limits.sh, mix.exs, tailscale/wrapper.sh
Startup script to set ulimit on proper user
=> fix: Startup script to set ulimit on proper user

lib/realtime_web/router.ex, mix.exs
=> fix: Sanitize token

lib/realtime/tenants.ex, lib/realtime_web/channels/realtime_channel.ex, mix.exs, test/integration/rt_channel_test.exs, test/support/generators.ex
=> fix: Change private topic format

README.md, lib/extensions/postgres_cdc_rls/replication_poller.ex, mix.exs
Pooling error not in the proper format
=> fix: Pooling error not in the proper format

lib/realtime/tenants/migrations.ex, lib/realtime/tenants/repo/migrations/20240618124746_fix_walrus_role_handling.ex, mix.exs
Fix walrus query to better handle roles
=> fix: Fix walrus query to better handle roles

lib/realtime_web/open_api_schemas.ex, mix.exs
Update OpenAPI docs for Broadcast
=> fix: Update OpenAPI docs for Broadcast

lib/realtime_web/endpoint.ex, mix.exs
Longpoll configuration setting properly session
=> fix: Longpoll configuration setting properly session

lib/realtime/tenants/listen.ex, mix.exs, test/realtime/tenants/listen_test.exs
Add more logs to Listen module
=> fix: Add more logs to Listen module

lib/realtime/tenants/listen.ex, mix.exs, test/realtime/tenants/connect_test.exs, test/realtime/tenants/listen_test.exs
Move to sync connection and added more tests to validate some behaviours regarding Listen module startup with feature flags.
=> fix: Move to sync connection

lib/realtime/tenants/listen.ex, mix.exs
=> fix: Use correct IP version

lib/realtime/tenants/listen.ex, mix.exs, test/realtime/tenants/connect_test.exs
=> fix: Properly set SSL options

lib/realtime/tenants/listen.ex, mix.exs, test/realtime/tenants/listen_test.exs
Listen on already existing conn; add application_name to conn
=> fix: Listen on already existing conn; add application_name to conn

lib/realtime/tenants/connect.ex, lib/realtime/tenants/listen.ex, mix.exs, test/realtime/tenants/connect_test.exs, test/realtime/tenants/listen_test.exs
Move to more restrictive listen
=> fix: Move to more restrictive listen

lib/realtime/tenants/listen.ex, mix.exs
=> fix: Ensure RateCounter starts

lib/realtime/tenants/listen.ex, mix.exs
=> fix: Start GenCounter properly

README.md, lib/realtime_web/controllers/fallback_controller.ex, mix.exs
Log errors on fallback controller
=> fix: Log errors on fallback controller

lib/realtime/tenants/listen.ex, mix.exs, test/realtime/tenants/listen_test.exs
=> fix: Set idle shutdown to infinity

lib/realtime_web/controllers/fallback_controller.ex, mix.exs
- adds a catchall in the FallbackController and logs unknown errors
=> fix: log unknown Broadcast errors

lib/realtime/database.ex, mix.exs
=> fix: avoid pool size override

lib/realtime/database.ex, lib/realtime/tenants/batch_broadcast.ex, mix.exs, test/realtime/database_test.exs, test/realtime/messages_test.exs, test/realtime/repo_test.exs, test/realtime/tenants/authorization/permissions/broadcast_policies_test.exs, test/realtime/tenants/authorization_test.exs, test/realtime/tenants/listen_test.exs, test/realtime/tenants/migrations_test.exs, test/support/generators.ex, test/support/tenant_connection.ex
Currently logs from transactions where not being properly managed so this fixes the issue
Also took the opportunity to clean up the code from the Database module to make it less error prone
=> fix: Sanitize logs and refactor database connection

mix.exs, priv/repo/seeds.exs
Allow setting selfhost jwt jwks value
=> fix: Allow setting selfhost jwt jwks value

README.md, lib/realtime/rpc.ex, mix.exs
erpc call returning tuple error throws jason encode issues
=> fix: erpc call returning tuple error throws jason encode issues

lib/realtime/nodes.ex, mix.exs
Additionally, sorts the region translations list.
=> fix: add translations for new regions

lib/realtime/operations.ex, mix.exs
To help debugging potential issues with processes being created without restrictions were adding a function to help debug those issues.
=> fix: Add dump process data function

mix.exs, priv/static/worker.js
=> fix: Change interval on workerjs

mix.exs, priv/static/worker.js
=> fix: Increase interval on workerjs

mix.exs, priv/repo/migrations/20240902173232_add_extension_external_id_index.exs, priv/static/worker.js, rel/vm.args.eex, test/realtime/extensions/cdc_rls/subscriptions_test.exs, test/support/generators.ex
* Remove `+sbwt` flag change until we handle a syn issue found in load testing
* Change `worker.js` implementation to receive the heartbeat time from configuration
* Add migration to create index for external_id on extensions - https://github.com/supabase/realtime/issues/1140
* Reduce test flakiness
=> fix: Multiple fixes

lib/realtime/rpc.ex, mix.exs, test/e2e/tests.ts
* Adds more details on RPC errors
* Fixes e2e tests by focusing on primary key vs non primary key fields
=> fix: Add more details to RPC errors & fix e2e

README.md, lib/realtime/tenants/connect.ex, lib/realtime_web/channels/realtime_channel.ex, mix.exs
=> fix: Add claim value to error log

lib/realtime/broadcast_changes/handler.ex, mix.exs
Set proper options for SSL connection
=> fix: Set proper options for SSL connection

lib/realtime/broadcast_changes/handler.ex, mix.exs, test/realtime/broadcast_changes/handler_test.exs, test/realtime/database_test.exs
=> fix: SSL options set properly

lib/realtime/broadcast_changes/handler.ex, mix.exs
=> fix: Use proper registry name

lib/realtime/broadcast_changes/handler.ex, lib/realtime/database.ex, lib/realtime/tenants.ex, lib/realtime/tenants/connect.ex, lib/realtime/tenants/connect/check_connection.ex, lib/realtime/tenants/connect/get_tenant.ex, lib/realtime/tenants/connect/migrations.ex, lib/realtime/tenants/connect/piper.ex, lib/realtime/tenants/connect/register_process.ex, lib/realtime/tenants/connect/start_counters.ex, lib/realtime/tenants/connect/start_replication.ex, mix.exs, test/realtime/broadcast_changes/handler_test.exs, test/realtime/tenants/connect/piper_test.exs
Add Plug like logic to Connect so we can pipe operations of the Connect operation to ensure we guarantee full operation of all features
=> fix: Adds plug like logic to Connect

.github/workflows/staging_linter.yml, lib/realtime/tenants.ex, mix.exs
Kill healthcheck conn after done
=> fix: Kill healthcheck conn after done

config/runtime.exs, lib/realtime/api/message.ex, lib/realtime/application.ex, mix.exs, test/realtime/tenants/janitor_test.exs
Default off on janitor task, some other changes that can be impacting service
=> fix: Default off on janitor task, some other changes that can be impacting service

lib/realtime/application.ex, lib/realtime/nodes.ex, lib/realtime_web/live/inspector_live/conn_component.html.heex, mix.exs
=> fix: Revert changes to nodes.ex

config/runtime.exs, mix.exs
=> fix: Invert janitor flag

lib/realtime/api/tenant.ex, lib/realtime/tenants.ex, lib/realtime_web/controllers/tenant_controller.ex, lib/realtime_web/router.ex, mix.exs, priv/repo/migrations/20241106103258_add_private_only_flag_column_to_tenant.exs, test/realtime/tenants_test.exs, test/realtime_web/controllers/tenant_controller_test.exs
Add endpoint for realtime configuration management
=> fix: Add endpoint for realtime configuration management

config/runtime.exs, mix.exs
- keeps Logger from going into sync mode
=> fix: sets some logger configs

lib/realtime/api/tenant.ex, lib/realtime/tenants.ex, lib/realtime_web/channels/realtime_channel.ex, lib/realtime_web/controllers/tenant_controller.ex, mix.exs, test/integration/rt_channel_test.exs, test/realtime/repo_test.exs
Implement private only check on socket connect
=> fix: Implement private only check on socket connect

.github/workflows/manual_prod_build.yml, lib/realtime/tenants/connect/start_counters.ex, mix.exs
Start counters with proper metadata
=> fix: Start counters with proper metadata

.github/workflows/manual_prod_build.yml, mix.exs
Avoid extra steps and extra images on custom build
=> fix: Avoid extra steps and extra images on custom build

.github/workflows/manual_prod_build.yml, mix.exs
Remove semver check from custom action
=> fix: Remove semver check from custom action

lib/realtime/api/message.ex, lib/realtime/broadcast_changes/handler.ex, lib/realtime/tenants.ex, lib/realtime/tenants/migrations.ex, lib/realtime/tenants/repo/migrations/20241108114728_messages_using_uuid.ex, mix.exs, test/realtime/tenants_test.exs
Changes the existing ID to UUID type.
=> fix: alter id to uuid type

lib/realtime/tenants/janitor.ex, mix.exs
Kill Janitor conns on process end
=> fix: Kill Janitor conns on process end

lib/realtime/helpers.ex, lib/realtime/rpc.ex, mix.exs
improve erpc log metadata on error
=> fix: improve erpc log metadata on error

lib/realtime/tenants.ex, lib/realtime/tenants/connect.ex, mix.exs
- doesn't retry 
- makes things a bit more obvious
=> fix: cleanup Connect.lookup_or_start_connection

lib/realtime/tenants/connect/piper.ex, mix.exs, test/realtime/tenants/connect/piper_test.exs
=> fix: Add log information on pipes

lib/realtime/tenants/connect/piper.ex, mix.exs
=> fix: Change time unit to ms

lib/realtime/tenants.ex, lib/realtime/tenants/cache.ex, lib/realtime/tenants/connect.ex, mix.exs
Add init warning; increase tenant cache to 6 hours
=> fix: Add init warning; increase tenant cache to 6 hours

lib/realtime/tenants/connect/migrations.ex, lib/realtime_web/channels/realtime_channel.ex, mix.exs, test/realtime/tenants/connect_test.exs
=> fix: Revert maybe run migrations

lib/realtime/tenants/connect/migrations.ex, mix.exs
=> fix: Comment migrations

lib/realtime/tenants.ex, lib/realtime/tenants/connect.ex, lib/realtime_web/templates/layout/live.html.heex, mix.exs, test/realtime/tenants/connect_test.exs, test/realtime_web/controllers/tenant_controller_test.exs
Add region to healthcheck; Better failure flow on Connect
=> fix: Add region to healthcheck; Better failure flow on Connect

README.md, lib/realtime/tenants/connect.ex, lib/realtime/tenants/migrations.ex, mix.exs
Improve logs on create partitioning code
=> fix: Improve logs on create partitioning code

lib/extensions/postgres_cdc_rls/cdc_rls.ex, lib/extensions/postgres_cdc_rls/replication_poller.ex, lib/extensions/postgres_cdc_rls/subscription_manager.ex, lib/extensions/postgres_cdc_rls/subscriptions.ex, lib/extensions/postgres_cdc_rls/subscriptions_checker.ex, lib/extensions/postgres_cdc_stream/cdc_stream.ex, lib/extensions/postgres_cdc_stream/replication.ex, lib/realtime/broadcast_changes/handler.ex, lib/realtime/database.ex, lib/realtime/gen_counter/gen_counter.ex, lib/realtime/helpers.ex, lib/realtime/logs.ex, lib/realtime/monitoring/latency.ex, lib/realtime/repo.ex, lib/realtime/rpc.ex, lib/realtime/tenants/authorization/policies/broadcast_policies.ex, lib/realtime/tenants/authorization/policies/presence_policies.ex, lib/realtime/tenants/batch_broadcast.ex, lib/realtime/tenants/connect.ex, lib/realtime/tenants/janitor.ex, lib/realtime/tenants/migrations.ex, lib/realtime_web/channels/auth/channels_authorization.ex, lib/realtime_web/channels/realtime_channel.ex, lib/realtime_web/channels/realtime_channel/logging.ex, lib/realtime_web/channels/user_socket.ex, lib/realtime_web/controllers/fallback_controller.ex, lib/realtime_web/controllers/tenant_controller.ex, mix.exs
Handle encoding error on DBConnect and Postgrex errors
=> fix: handle encoding error

README.md, lib/realtime/database.ex, lib/realtime/rpc.ex, lib/realtime_web/channels/realtime_channel.ex, lib/realtime_web/controllers/fallback_controller.ex, mix.exs
Improve errors logged out and erpc error handling
=> fix: Improve errors logged out and erpc error handling

lib/realtime_web/channels/realtime_channel.ex, mix.exs
Improve error handling on realtime channel
=> fix: Improve error handling on realtime channel

lib/realtime/api.ex, lib/realtime_web/channels/realtime_channel.ex, mix.exs, test/integration/rt_channel_test.exs, test/realtime/api_test.exs
Shutdown tenant sockets on jwks or jwt_secret changes
=> fix: Shutdown tenant sockets on jwks or jwt_secret changes

lib/realtime_web/channels/realtime_channel.ex, mix.exs
Improve handling of realtime_channel.ex on transaction error
=> fix: Improve handling of realtime_channel.ex on transaction error

README.md, lib/realtime_web/channels/realtime_channel.ex, mix.exs, test/integration/rt_channel_test.exs
=> fix: Prevent empty topics

lib/realtime/metrics_cleaner.ex, mix.exs
=> fix: cleanup hanging ecto metrics

lib/realtime/tenants/listen.ex, mix.exs
Handle SSL and IP Version properly on Listen Notify
=> fix: Handle SSL and IP Version properly on Listen Notify

lib/extensions/postgres_cdc_rls/replication_poller.ex, lib/extensions/postgres_cdc_rls/subscription_manager.ex, lib/extensions/postgres_cdc_rls/subscriptions_checker.ex, mix.exs
Async postgres changes process startup
=> fix: Async postgres changes process startup

lib/realtime/tenants/replication_connection.ex, mix.exs, test/support/cleanup.ex
Remove replication slot teardown from disconnect
=> fix: Remove replication slot teardown from disconnect

lib/realtime_web/channels/auth/channels_authorization.ex, lib/realtime_web/channels/auth/jwt_verification.ex, lib/realtime_web/channels/realtime_channel.ex, lib/realtime_web/channels/user_socket.ex, mix.exs, test/integration/rt_channel_test.exs, test/realtime_web/channels/auth/jwt_verification_test.exs, test/realtime_web/channels/realtime_channel_test.exs
improve error logs for expired tokens
=> fix: improve error logs for expired tokens

config/test.exs, lib/realtime/tenants/connect.ex, lib/realtime_web/channels/realtime_channel.ex, lib/realtime_web/channels/realtime_channel/broadcast_handler.ex, lib/realtime_web/channels/realtime_channel/logging.ex, lib/realtime_web/channels/user_socket.ex, mix.exs, test/integration/rt_channel_test.exs, test/realtime_web/channels/realtime_channel_test.exs
Add sub to log metadata; adds tests to rate limits
=> fix: Add sub to log metadata; adds tests to rate limits

lib/realtime_web/channels/realtime_channel.ex, test/integration/rt_channel_test.exs
=> fix: Missing unauthorized match

lib/realtime_web/channels/realtime_channel.ex, lib/realtime_web/channels/user_socket.ex, mix.exs
=> fix: log error on invalid jwt

lib/realtime_web/controllers/tenant_controller.ex, mix.exs, test/realtime_web/controllers/tenant_controller_test.exs
suspend before delete to trigger killing all related processes
=> fix: suspend before delete to trigger killing all related processes

lib/realtime_web/controllers/tenant_controller.ex, mix.exs, test/realtime_web/controllers/tenant_controller_test.exs
Delete after suspend to prevent wrong cache values
=> fix: Delete after suspend to prevent wrong cache values

config/config.exs, mix.exs, test/realtime/tenants/replication_connection_test.exs
Restrict information shown by Phoenix logger
=> fix: Restrict information shown by Phoenix logger

lib/realtime/database.ex, lib/realtime/rpc.ex, lib/realtime_web/channels/auth/channels_authorization.ex, mix.exs, test/integration/rt_channel_test.exs, test/realtime/database_test.exs, test/realtime_web/channels/realtime_channel_test.exs
Handle missed match on database rpc
=> fix: Handle missed match on database rpc

.github/workflows/mirror.yml, .github/workflows/prod_build.yml, .github/workflows/prod_linter.yml, .github/workflows/tests.yml, .github/workflows/version_updated.yml
Currently the permissions are not properly tuned so we will remove to unblock us for now
=> fix: Remove GH permissions temporarly

.github/workflows/prod_build.yml, .github/workflows/tests.yml, .github/workflows/version_updated.yml, lib/realtime/application.ex, lib/realtime/nodes.ex, lib/realtime/syn_handler.ex, lib/realtime/tenants/connect.ex, lib/realtime/tenants/connect/register_process.ex, test/realtime/syn_handler_test.exs, test/realtime/tenants/connect/register_process_test.exs, test/support/clustered.ex
handle regionless state in syn & non found process on register_process
=> fix: handle regionless state in syn & non found process on register_process

lib/realtime/database.ex, mix.exs, test/e2e/tests.ts, test/realtime/database_test.exs
since db_pool is already used for the connect checks it does not make sense to account for it in our limits
=> fix: does not take into consideration db_pool

test/e2e/README.md
=> chore: update e2e/README.md

test/e2e/README.md, test/e2e/tests.ts
Cleans up E2E tests and makes them faster to run (previously 1+ minute, now 16 seconds)
=> chore: speedup and clean e2e tests

assets/js/app.js, lib/realtime_web/live/inspector_live/conn_component.ex, lib/realtime_web/live/inspector_live/conn_component.html.heex, lib/realtime_web/live/inspector_live/index.ex, mix.exs
add private toggle on inspector to improve debugging capabilities
=> fix: add private toggle on inspector to improve debugging capabilities

assets/package-lock.json, assets/package.json, mix.exs
=> fix: bump up supabase-js

lib/realtime/telemetry/logger.ex, lib/realtime_web/channels/realtime_channel.ex, mix.exs, test/integration/rt_channel_test.exs
* presence events are now logged
* we were not handling properly nil pg_changes
=> fix: send presence logs; fix nil pg_params error

test/realtime/tenants/authorization_remote_test.exs, test/realtime/tenants/authorization_test.exs
Reduce the amount of time we wait to cause a database timeout on. the authorization tests. Each test was using ~1 minute each and one of them can't run async
=> chore: speed up authorization tests

lib/realtime/api.ex, mix.exs, test/integration/rt_channel_test.exs, test/realtime/api_test.exs
private_only flag change triggers socket disconnect
=> fix: private_only flag change triggers socket disconnect

test/support/containers.ex
Otherwise repeat-until-failure would hit limits
pg_terminate_backend was just restarting the db connections as Postgrex will keep restarting them.
=> chore: fix connection teardown on tests

test/integration/rt_channel_test.exs
No need to skip those tests anymore
=> chore: run rate counter integration tests

lib/realtime_web/channels/realtime_channel.ex, lib/realtime_web/channels/realtime_channel/logging.ex, lib/realtime_web/channels/user_socket.ex, mix.exs, test/integration/rt_channel_test.exs, test/realtime_web/channels/realtime_channel/logging_test.exs
move invalid jwt log to warning level
=> fix: move invalid jwt log to warning level

config/config.exs, config/dev.exs, config/prod.exs, config/runtime.exs, config/test.exs, lib/realtime/application.ex, lib/realtime_web/channels/realtime_channel.ex, lib/realtime_web/channels/realtime_channel/logging.ex, lib/realtime_web/channels/realtime_channel/presence_handler.ex, lib/realtime_web/channels/user_socket.ex, lib/realtime_web/views/error_view.ex, mix.exs, test/integration/rt_channel_test.exs, test/realtime_web/channels/realtime_channel/logging_test.exs, test/realtime_web/channels/realtime_channel_test.exs
Refactor Logging module to simplify the logic into a simpler methods and cleaned up the internal logic. Also all logs will include JWT metadata from now on.
=> fix: simplify logging approach

lib/realtime_web/channels/realtime_channel/presence_handler.ex, mix.exs
further decrease limit on presence events
=> fix: further decrease limit on presence events

mix.exs
=> fix: bump up realtime
