- server/lib/realtime/application.ex
- server/lib/realtime/replication.ex
- server/lib/realtime/subscribers_notification.ex
This is related to #33.
I moved the notification logic to a separate genserver that is a sibling of the replication genserver.
> Move realtime subscribers notification to separate module

- server/lib/realtime/application.ex
As mentioned in #34, I think this is the best way for realtime to pickup from where it left after a restart.
> Add configuration option to use named replication slots

- README.md
- server/config/releases.exs
- server/lib/realtime/application.ex
This will probably be affected by #48 in the future, but for now we should follow the recommended way to set runtime configs as explained [here](https://hexdocs.pm/mix/1.9.0/Mix.Tasks.Release.html#module-runtime-configuration).
Closes #31.
> refactor: extract runtime config to releases.exs

- server/config/config.exs
- server/config/releases.exs
- server/lib/realtime/application.ex
The config handling in #52 was incorrect, so this PR is to remedy that. Other changes I made:
- Moved the handling of unset envs to `config.exs` and `releases.exs`--this shouldn't be `application.ex`'s concern as default values can be set at build/release.
- It should now be possible to run the app with `mix phx.server` (without using mix releases). On the flip side, the configs in `config.exs` (used in `mix phx.server`) should mirror the defaults in `releases.exs` (used in `mix release`).
> fix: incorrect env config handling

- README.md
We still need to benchmark this server before we can really put it in Beta
Updates the project status
Docs say we're in Beta
We should keep this in Alpha until we have benchmarked, then put ALL of supabase into Beta when all benchmarks are completed
> Moves server to alpha

- README.md
- server/README.md
- server/config/config.exs
- server/lib/adapters/postgres/epgsql_implementation.ex
- server/lib/realtime/application.ex
Fixes #22 
The `SLOT_NAME` variable is getting converted to lowercase in Postgres, so when the server is trying to `SELECT` an existing slot it isn't matching correctly.
This converts the `SLOT_NAME` to lower case and adds instructions that it should always be lower case.
Long shot: this could possibly solve https://github.com/supabase/realtime/issues/61 if the disk usage is caused by connecting/reconnecting, causing Postgres to create a lot of different temporary slots.
> fix: converts the slot_name to lower case so that it matches Postgres

- dev/postgres/mnt/init-permissions.sh
- examples/next-js/pages/index.js
- server/lib/realtime/configuration.ex
- server/lib/realtime/subscribers_notification.ex
Feature.
Closes #73.
Default config is:
```elixir
realtime: [
%Realtime{
event: "*",
relation: "*"
},
%Realtime{
event: "*",
relation: "*:*"
},
%Realtime{
event: "*",
relation: "*:*:*"
}
]
```
This allows all events to be broadcasted to all room types:
- `realtime:*`
- `realtime:<schema>`
- `realtime:<schema>:<table>`
- `realtime:<schema>:<table>:<column>`
I removed the leading `realtime:` for `relation` from our discussion. Looks cleaner imo, but let me know if you want to add it back.
One problem: there's no way to 1. allow events to `realtime:*`, and 2. allow events only for specific schemas, at the same time. This is because the relevant config `relation` is the same: `*`
> Support event filter

- server/lib/realtime/replication.ex
- server/lib/realtime/subscribers_notification.ex
- server/test/realtime/replication_test.exs
Bug fix
Every webhook change record's commit_timestamp is set to null:
```
{
"changes": [
{
"columns": [
{
"flags": [
"key"
],
"name": "id",
"type": "int8",
"type_modifier": 4294967295
},
{
"flags": [],
"name": "details",
"type": "text",
"type_modifier": 4294967295
},
{
"flags": [],
"name": "user_id",
"type": "int8",
"type_modifier": 4294967295
}
],
"commit_timestamp": null,
"record": {
"details": "If we generate the monitor, we can get to the SMS array through the online CSS circuit!",
"id": "1",
"user_id": "1"
},
"schema": "public",
"table": "todos",
"type": "INSERT"
}
],
"commit_timestamp": "2020-12-15T20:50:03Z"
}
```
Every webhook change record's commit_stamp is set to the transaction's commit_timestamp:
```
{
"changes": [
{
"columns": [
{
"flags": [
"key"
],
"name": "id",
"type": …
```
> Set commit_timestamp value for every change record

- .github/workflows/release.yml
- Breaks out build jobs into separate github jobs to allow for parallel execution, given there are no inter-dependencies
- Adds a new arm64 docker build
- Pins the OS for the native x86 build to u18 (from ubuntu-latest), which I _believe_ will imminently break once u-latest moves to u20 https://github.com/actions/virtual-environments/issues/1816
The arm64 docker build is only executed on releases, so the increased CI times shouldn't present a significant overhead for iterating on PRs. Additionally, an extremely straightforward speed-up would be to publish a base docker image with the appropriate OTP/elixir versions installed on the u18 base.
Note that unlike our other services, were publishing a separate tarball for arm64 here, rather than a single tarball with two binaries.
Fixes #86 
On …
> Build arm64 binaries

- server/lib/realtime/configuration.ex
- server/lib/realtime/subscribers_notification.ex
- server/test/realtime/configuration_test.exs
- server/test/realtime_web/channels/realtime_channel_test.exs
Bug fix.
[This code](https://github.com/supabase/realtime/blob/1220728423ed012ca9dfcd18e79188e4bb96e1fe/server/lib/realtime/subscribers_notification.ex#L74-L98) is not happy when it receives a `TRUNCATE` event. `TRUNCATE` events are not broadcasted.
`TRUNCATE` events are broadcasted (added the event type in the default config). Event filters are applied (schema and table only). A `TRUNCATE` event looks like this on the client:
```json
{
"commit_timestamp": "2021-01-06T17:26:35Z",
"schema": "public",
"table": "bar",
"type": "TRUNCATE"
}
```
Re: the discussion on Slack: turns out I was wrong, the decoder + adapter handles `TRUNCATE` in a way that also gives schema and table information. The resulting `TruncatedRelation` is what's received in `SubscribersNotification`.
> fix: handle TRUNCATE events

- README.md
Realtime README update
Breaking change is v0.9.8
Breaking change is v0.10.0
Assumed the next release was going to be v0.9.8 but it's actually v0.10.0.
> Update Realtime README breaking change version from 0.9.8 to 0.10.0

- server/lib/realtime/replication.ex
- server/test/realtime/replication_test.exs
Bug fix.
When the application fails to connect to the DB at start up (`:econnrefused`), it crashes. This is because `handle_continue/2` returns a `:stop` instead of falling back to the `:EXIT` trap.
Failing to connect during `init` will run the retry logic instead of crashing.
@w3b6x9 would love to hear your input here. Is this the right behavior?
> fix: replication fails to trap on :init_db_conn

- server/lib/decoder/decoder.ex
- server/lib/realtime/replication.ex
- server/test/decoder/decoder_test.exs
Bug fix
Selecting Cascade and Restart Identity when truncating data from table results in the following error: `(CaseClauseError) no case clause matching: 3`
Addresses issue #102. 
Selecting Cascade and Restart Identity when truncating data from table doesn't raise error and everything works as expected.
- Tested to make sure both realtime channel and webhook messages contained the right commit timestamps.
- `%Truncate{}` options (e.g. `2 -> [:restart_identity]`) aren't used anywhere else so we can consider removing altogether.
- I did some refactoring while making sure that all the Changes (i.e. `NewRecord`, `UpdatedRecord`, `DeletedRecord`, `TruncatedRelation`) had `commit_timestamp`s during creation.
> Add Truncate option 3 and add commit_timestamp to all DB Changes

- Dockerfile
- README.md
- docker-compose.dev.yml
- examples/next-js/docker-compose.yml
- examples/node-js/docker-compose.yml
Docs update
`SECURE_CHANNELS` and `JWT_CLAIM_VALIDATORS` are labeled as `string` values.
I think this is the better call considering they technically are strings coming in, and the application picks it up and converts them to boolean and JSON object.
Related issue: #107
> Convert SECURE_CHANNELS value from boolean to string

- examples/next-js/package-lock.json
- examples/next-js/package.json
- examples/next-js/pages/index.js
Chore
Replace `Socket` with `RealtimeClient` from `@supabase/realtime-js`
Did this as I was confirming https://github.com/supabase/realtime/issues/109
> chore: version bump @supabase/realtime-js to 1.0.6

- server/lib/decoder/oid_database.ex
refactor
Uses `DataTypes` struct and `Map.has_key?/2` to look up OID.
Uses `case` to look up OID. This is more performance.
Refactor suggested by @abc3 in issue #116
> refactor: improve oid database lookup performance

- server/lib/realtime_web/channels/user_socket.ex
- server/test/realtime_web/channels/user_socket_test.exs
feature
socket param auth token key is 'token'
socket param auth token key is 'apikey'
Related issue: #95
> feat: change socket param from token to apikey

- .github/workflows/release.yml
Fixes https://github.com/supabase/cli/issues/23
There is no docker build shipped for ARM architectures, so the realtime container fails when running the CLI on M1 Macs.
Building a docker images locally fixes the issue, this _should_ publish a compatible image for ARM architectures to Docker Hub.
> fix: Add docker image for arm64 architectures

- .github/workflows/ci.yml
- .github/workflows/release.yml
Update action from `actions/setup-elixir@v1` to `erlef/setup-beam@v1` to fix failing Elixir setup step.
Elixir setup is failing with the following error:
> Error: 2.433 [error] Unable to load crypto library. Failed with error:
> ":load_failed, Failed to load NIF library /home/runner/work/_temp/.setup-elixir/otp/lib/crypto-4.6.5/priv/lib/crypto: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'"
> OpenSSL might not be installed on this system.
Elixir setup succeeds and CI passes.
`actions/setup-elixir@v1` is no longer maintained and `erlef/setup-beam@v1` is recommended. See https://github.com/actions/setup-elixir for more details.
> Update Elixir actions in release.yml and ci.yml to erlef/setup-beam@v1

- server/lib/realtime/application.ex
Bug fix
connect to db via IPv6 on occasion as well as via IPv4.
connect to db via IPv4 only.
> fix: specify db connect via IPv4

- examples/node-js/src/server.js
Example/docs minor typo fix in a log
Says "UPDATE" when listening to "DELETE"
Says "DELETE" when listening to "DELETE"
Node server example file
> copy pasta fix

- examples/node-js/src/server.js
Example/docs cleanup
Runs empty interval timer every 10 seconds
Not to do that
The listeners added throughout the file take care of this [via the Event Loop](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#phases-overview).  If you are seeing otherwise, your connections are probably closing unexpectedly and require monitoring + logging out of the scope of a simple example server.
Node server example file
> remove unnecessary setInterval()

- README.md
- server/config/config.exs
- server/config/releases.exs
- server/lib/realtime/application.ex
feature
User can't pass in the IP version they want to use to connect to db.
User can pass in either IPv4 or IPv6 in order to connect to db.
> feat: enable IP version specification for DB connect

- examples/node-js/docker-compose.yml
Set SECURE_CHANNELS to `'false'` in node js example `docker-compose.yml`
Related issue: https://github.com/supabase/realtime/issues/150
> Set SECURE_CHANNELS to false in node example

- README.md
- server/lib/adapters/postgres/epgsql_server.ex
Bug fix
Database deletes a WAL segment that Realtime server still needs to replay. Realtime is caught restarting in a loop as it cannot find the WAL segment.
Database deletes a WAL segment that Realtime server still needs to replay. Realtime recognizes this, drops the replication slot, and on restart a new replication slot is created. All is normal again.
- Re-creating a standby (Realtime server) that falls behind is a suggested solution (see https://www.2ndquadrant.com/en/blog/postgresql-9-4-slots for more details)
- There's no good way to test this live so we'll just have to see if it resolves the issue after deploying.
> fix: drop replication slot when db deletes wal segment

- README.md
- server/config/config.exs
- server/config/releases.exs
- server/lib/adapters/postgres/epgsql_server.ex
- server/lib/realtime/application.ex
Prod improvement
Running on a production instance, a big replication lag will use a lot of CPU and continuously crash Realtime due to instance memory limits.
Running on a production instance, when a big replication lag exceeds a set limit (`MAX_REPLICATION_SLOT_MB`), then replication slot will be dropped, Realtime will be restarted, and a new slot will be created. This will allow the instance to keep operating as normal.
**WARNING**: Setting `MAX_REPLICATION_SLOT_MB` could cause database changes to be lost when the replication slot is dropped.
> fix: drop replication slot when lag exceeds max replication lag value

- server/config/prod.exs
Bug fix
client is unable to connect to realtime websocket in prod due to domain origin check by default.
client is able to connect to realtime websocket in prod by allowing all domains to connect.
This is caused by removing `url: [host: Application.get_env(:demo, :app_hostname), port: Application.get_env(:demo, :app_port)]` from `prod.exs`
> fix: set :check_origin to false in prod.exs

- server/lib/realtime_web/channels/realtime_channel.ex
- server/test/realtime_web/channels/realtime_channel_test.exs
feature
Txn change is broadcast to both * and specific type (INSERT/UPDATE/DELETE)
Txn change is broadcast only specific type (INSERT/UPDATE/DELETE)
- Related PR: https://github.com/supabase/realtime-js/pull/75
- `realtime-js` v1.0.7 was version bumped in `supabase-js` via this commit: https://github.com/supabase/supabase-js/commit/22a9c030b4fef6395e69efaa21b4baba693cf05f
> feat: remove all (*) event broadcasting

- server/config/config.exs
- server/lib/realtime/application.ex
- server/lib/realtime/helpers.ex
- server/lib/realtime/webhook_connector.ex
- server/test/helpers_test.exs
- server/test/realtime/webhook_connector_test.exs
There are use cases where it needs to add custom headers to Webhook, for example, for authentication. This code implements it through the environment variable `WEBHOOK_HEADERS`. Colon `:` used for split multiple headers.
The `key1=value1:key2=value2` will transform to `[{"key1", "value1"},{"key2", "value2"}]`
In the current behavior used the only one additional header `[{"content-type", "application/json"}]`
In new behavior, there is checking the value of `WEBHOOK_HEADERS` variable, and if it's not empty and valid, then it adds to the webhook request. 
If the application has started with `WEBHOOK_HEADERS=key1=value1:key2=value2`, the request on the server part looks like this:
> feat: Add headers to the Webhook request

- server/lib/realtime_web/channels/realtime_channel.ex
Bug fix
`access_token` messages are not handled by channel processes.
`access_token` messages are handled by channel processes until Realtime security (WALRUS) is shipped.
Related PR: https://github.com/supabase/realtime-js/pull/116
> fix: handle incoming access_token message from client

- server/priv/repo/migrations/20211124070109_enable_realtime_apply_rls_function_postgrest_9_compatibility.exs
Chore
Update `realtime.apply_rls` Postgres function for PostgREST 9 compatibility.
See related PR: https://github.com/supabase/walrus/pull/24
Added comments below as to where the changes are. Otherwise, it's a copy/paste of `20211116214523_create_realtime_apply_rls_function.exs`.
> chore: update apply_rls function for PostgREST 9 compatibility

- server/lib/realtime_web/channels/user_socket.ex
- server/lib/realtime_web/endpoint.ex
- server/test/realtime_web/channels/user_socket_test.exs
This PR adds the possibility to get access token from x-api-key request header. 
The current behavior uses GET parameters "apikey" or "token" for passing token to the `RealtimeWeb.ChannelsAuthorization`.
The new behavior gets token from `X-API-Key` request header. Also, previous behavior stays for backward compatibility and can be removed in the future.
`Realtime` issue: https://github.com/supabase/realtime/issues/186
`realtime-js` issue: https://github.com/supabase/realtime-js/issues/108
> Use X-API-Key header param for authenticating

- server/lib/realtime/subscribers_notification.ex
- server/test/realtime/subscribers_notification_test.exs
Bug fix
Column types, such as `json`/`jsonb`, are not properly handled by Realtime filters, resulting in raised errors.
Column types, such as `json`/`jsonb`, are properly handled.
When subscribing to a `json` column make sure to strip whitespace.
For example, if a `json` column named `details` on `public.test` table has a new insert:
`[{"a": 1}]`
then changes will be received when listening to inserts on topic `realtime:public:details=eq.[{"a":1}]`.
> fix: handle filters when column is any type

- server/config/config.exs
This PR allows setting the maximum number of active connections through the Ranch [max_connections](https://ninenines.eu/docs/en/ranch/1.7/manual/ranch/) parameter.
In current behavior, `Plug.Cowboy` uses the default [16_384](https://github.com/elixir-plug/plug_cowboy/blob/040c53f45bdbd3f1afe9f449fa1cb3b54294e7fb/lib/plug/cowboy.ex#L45) value.
In new behavior, it's possible to set any maximum number of active connections if start Realtime with environment variable MAX_CONNECTIONS. Soft limit.
By default, it uses 16_384 as earlier.
> Set the maximum number of active connections

- server/lib/realtime/rls/replication_poller.ex
- server/lib/realtime/rls/replications.ex
- server/test/realtime/rls_replications_test.exs
Bug fix
Postgres error when calling a Postgres function containing non-schema-qualified table name (e.g. referencing `test` instead of `public.test`) inside a RLS policy because `search_path` is set to `''`
Realtime RLS works when calling a Postgres function containing non-schema-qualified table name (e.g. referencing `test` instead of `public.test`) inside a RLS policy. This is resolved by removing setting `search_path` to `''`.
Related issues:
- [realtime only emitting DELETE events (no INSERT or UPDATE) #213](https://github.com/supabase/realtime/issues/213)
- [Realtime broken when policy use custom SQL functions #4683](https://github.com/supabase/supabase/issues/4683)
Related PR:
- https://github.com/supabase/walrus/pull/35
> fix: remove setting search path before replication

- server/priv/repo/migrations/20220107221237_update_change_timestamp_to_iso_8601_zulu_format.exs
Bug fix
timestamp is in the following example format:
```
2022-01-07T02:24:31.114082+00:00
```
timestamp is in iso 8601 zulu format. example format:
```
2022-01-06T05:49:57Z
```
Related issue: https://github.com/supabase/walrus/issues/37
> fix: update change timestamp to ISO 8601 Zulu format

- server/config/config.exs
- server/config/releases.exs
chore
add `queue_target` to help out longer transactions when database under heavy load.
see: https://elixirforum.com/t/ecto-query-timeout/27946/6
> chore: add db queue_target param

- server/lib/realtime/rls/replication_poller.ex
- server/priv/repo/migrations/20211228014915_add_wal_payload_on_errors_in_apply_rls_function.exs
- server/test/realtime/replication_poller_test.exs
feature
Broadcast messages with errors. Check https://github.com/supabase/walrus#error-states for possible errors.
> feat: broadcast messages with errors

- server/lib/realtime/rls/subscriptions/subscriptions.ex
Bug fix
truncate causes intermittent database fluctuations
replacing truncate with delete prevents database fluctuations
> fix: prevent db size fluctuations with delete instead of truncate

- server/priv/repo/migrations/20220228202821_update_subscription_check_filters_function_dynamic_table_name.exs
Bug fix
`ERROR:  column "<some column>" of relation "<some table>" does not exist`
Related PR: https://github.com/supabase/walrus/pull/44
> fix: use dynamic table name in subscription permissions check

- server/lib/adapters/changes.ex
- server/lib/realtime/message_dispatcher.ex
- server/lib/realtime/replication.ex
- server/lib/realtime/rls/replication_poller.ex
- server/test/realtime/message_dispatcher_test.exs
- server/test/realtime/replication_poller_test.exs
- server/test/realtime/replication_test.exs
- server/test/realtime/subscribers_notification_test.exs
- server/test/realtime_web/channels/realtime_channel_test.exs
Bug fix
When RLS is disabled for a table and there are multiple database roles subscribed to Realtime (e.g. one `anon` user and `authenticated` user) then clients will receive duplicate messages for the same change.
Clients will receive a single message for the same change regardless of which database roles are subscribed.
Related issue: https://github.com/supabase/realtime/issues/236
> fix: prevent duplicate broadcast when multiple roles are subscribed

- server/priv/repo/migrations/20220312004840_update_apply_rls_function_to_apply_iso_8601.exs
Bug fix
Migration `20211228014915_add_wal_payload_on_errors_in_apply_rls_function` was applied after `20220107221237_update_change_timestamp_to_iso_8601_zulu_format`
New migration will update the `apply_rls` WALRUS function to the latest.
> fix: update apply_rls function to convert timestamp to ISO 8601

- examples/next-js/README.md
Point .3 in `examples/next-js/README.md` mentions creating `.env` file which does not work. Should be `.env.local`
Bug fix
API requests from nextjs client fail because environment variables are not set (because README says to create `.env` which does not get detected when running `npm run dev`)
Works (environment variables are read from correct file `.env.local`
> Config file name should be .env.local

- docker-compose.db.yml
- docker-compose.dev.yml
- docker-compose.rls.dev.yml
- server/lib/realtime/rls/replications.ex
- server/priv/repo/migrations/20220603231003_add_quoted_regtypes_support.exs
- server/priv/repo/migrations/20220603232444_add_output_for_data_less_than_equal_64_bytes_when_payload_too_large.exs
- server/priv/repo/migrations/20220615214548_add_quoted_regtypes_backward_compatibility_support.exs
- server/test/realtime/rls_replications_test.exs
Bug fix
1. Realtime WALRUS doesn't work with quoted regtypes. This has been a huge pain point for developers who use Prisma.
2. When payload size too large developers don't get enough information on the client.
1. Realtime WALRUS works with quoted regtypes ([WALRUS PR](https://github.com/supabase/walrus/pull/46))
2. When payload size too large developers receive columns whose payload size is less than or equal to 64 bytes ([WALRUS PR](https://github.com/supabase/walrus/pull/47))
Related issues:
1. https://github.com/supabase/supabase/issues/5685#issuecomment-1142714282
2. https://github.com/supabase/realtime/issues/252
> fix: add quoted regtype support and output when payload too large

- server/lib/realtime/rls/subscriptions/subscriptions.ex
[Hotfix for Security] Changing table name to fetch database roles.
- It improve security to use `pg_roles` insted of `pg_authid`. 
- `pg_roles` is the view without password of `pg_authid` 
- It enable to work with Amazon RDS/Aurora.
- Because you can't have permission to read `pg_authid` table on Amazon RDS/Aurora.
Using `pg_authid` table.
https://github.com/supabase/realtime/issues/270
Using `pg_roles` table.
> Replace pg_authid table for pg_roles

- server/lib/realtime/message_dispatcher.ex
- server/lib/realtime/rls/replication_poller.ex
- server/lib/realtime/rls/subscriptions/subscriptions.ex
- server/lib/realtime/subscription_manager.ex
- server/lib/realtime_web/channels/realtime_channel.ex
- server/test/realtime/message_dispatcher_test.exs
- server/test/realtime/rls_subscriptions_test.exs
- server/test/realtime/subscription_manager_test.exs
- server/test/realtime_web/channels/realtime_channel_test.exs
feature
Update `Realtime.RLS.Subscriptions` to use a single query for inserting topic subscribers into `realtime.subscription`
> feat: simplify topic subscriptions insert query

- server/lib/realtime_web/channels/realtime_channel.ex
Bug fix
Duplicate messages are sent b/c channel is unsubscribing from topic  in `join/3` which overwrites the unsubscribe.
Channel is unsubscribing in `:after_join` which cleanly unsubscribes.
Fixes: https://github.com/supabase/realtime/issues/287
> fix: subscribe to :subscriber_fastlane in channel :after_join message

- Dockerfile
- docker-entrypoint.sh
This PR is to add an entry point file `docker-entrypoint.sh` to Docker image, which will enable use of Docker file-based secrets as mentioned in https://github.com/supabase/supabase/issues/6014.
Currently this Docker image only supports environment variable based secrets, file-based secrets `*_FILE` are not supported but is suggested by Docker in https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images.
File-based Docker secrets `*_FILE` will be supported and fall back to environment variable secrets.
N/A
> feat: support docker file-based secrets

- README.md
Fixed the Broken Image In README.md.
Updated specifying images based on the theme with new method  by using the HTML `<picture>` element in combination with the prefers-color-scheme media feature.
The old method of specifying images based on the theme, by using a fragment appended to the URL (#gh-dark-mode-only or #gh-light-mode-only), is deprecated and will be removed in favor of the new method described above.
[Source](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)
Broken Image In README.md.
Updated Broken Images & Specifying the theme with prefers-color-scheme
> Updated Broken Images & Specifying the theme with prefers-color-scheme

- README.md
- server/config/releases.exs
feature
Machine which does not support IPv6 can't run realtime due to there is no options for this.
User can specify IP version for realtime app.
Default behavior does not change.
I'm new to supabase, and does not have any experience on Elixir and Phoenix.
Is there any possible issue when realtime is binded to IPv4?
> feat: enable IP version specification for realtime app

- .github/workflows/mirror.yml
GHA workflow
supports running one off action to mirror specific image tags: `v0.22.7` is [needed](https://github.com/supabase/cli/issues/429)
similar to https://github.com/supabase/postgres/blob/develop/.github/workflows/mirror.yml
> chore: add ci job to mirror docker images to ecr

- docker-compose.db.yml
- docker-compose.dev.yml
- docker-compose.rls.dev.yml
Chore
`supabase/postgres` docker image is bumped up to 14.1.0.77.
> chore: upgrade supabase/postgres image version to 14.1.0.77

- .github/workflows/mt_prod.yml
Chore
Upload docker image error due to segmentation fault.
Hopefully, both arm64 and amd64 are deployed.
- https://github.com/supabase/realtime/actions/runs/3432087293/jobs/5721071413
> chore!: split up qemu and buildx steps in Multi-Tenant prod workflow

- config/runtime.exs
feature
Run any query immediately after connecting to Realtime Multi-Tenant database.
> feat: add after_connect to Realtime DB Repo config

- Dockerfile
- tailscale/wrapper.sh
Functionality is behind a ENABLE_TAILSCALE env var, without which we do not attempt to start tailscale. This should cater for self-hosted setups that don't require tailscale.
> feat: includes tailscale for private connections

- mix.exs
chore
remove unnecessary compilers due to upgrade to elixir v1.14
See: https://gist.github.com/chrismccord/00a6ea2a96bc57df0cce526bd20af8a7#remove-the-phoenix-and-gettext-compilers-from-your-mixexss-project0-compilers-configuration
> chore: remove compilers from mix.exs

- lib/realtime/repo.ex
feature
Fly `gru` (São Paulo) nodes are reading from AWS ap-southeast database
Fly `gru` nodes are reading from AWS us-east database replica
> feat: enable Fly gru region nodes to read from closest db replica

- Makefile
- config/dev.exs
- lib/realtime/application.ex
- lib/realtime/monitoring/latency.ex
- lib/realtime_web/live/page_live/index.html.heex
- lib/realtime_web/live/status_live/index.ex
- lib/realtime_web/live/status_live/index.html.heex
- lib/realtime_web/router.ex
- test/realtime/latency_test.exs
Problem: 
It's difficult to understand when our host is having subtle networking issues.
Solution:
We now have a GenServer to ping each node in the cluster from each node every 5 seconds. 
It logs:
- when the rpc fails
- when the latency of the rpc is over a certain value
We also have a LiveView to see realtime latencies between all nodes on a matrix:
> Feat: cluster latency matrix

- lib/extensions/postgres_cdc_rls/subscriptions.ex
- test/realtime/extensions/cdc_rls/subscriptions_test.exs
Problem: 
It was hard to tell which subscription params we supported.
Solution:
Tests, and being more explicit about what is failing when we parse subscription params.
> Feat: validate subscription params a bit more

- lib/extensions/postgres_cdc_rls/syn_handler.ex
The conflict is resolved in the same process as registration. This PR tries to stop the supervisor tree in the background to avoid a timeout on the `register_or_update_on_node` message.
> Fix: do not block a registration process

- .github/workflows/prod.yml
- .github/workflows/staging.yml
- .github/workflows/staging_supabench.yml
- Dockerfile
- Makefile
- lib/extensions/postgres_cdc_rls/replication_poller.ex
- test/realtime/extensions/cdc_rls/replication_poller_test.exs
Problem:
Sometimes during deployment two nodes try to connect to the same replication slot.
Solution:
Let's append the short git sha to the slot name. Now every new deployment will create an additional replication slot. And since we use temporary replication slots when nothing is connected to the old slot it should kill itself.
> Feat: append short commit sha to slot name

- priv/repo/migrations/20221223010058_drop_tenants_uniq_external_id_index.exs
Bug fix
There are two unique indexes on the same column, `external_id`, in the `tenants` table: `tenants_external_id_index (external_id)` and `uniq_external_id (external_id)`.
There is one unique index on the `external_id` column in the `tenants` table: `tenants_external_id_index (external_id)`.
> fix: remove uniq_external_id index from tenants table

- lib/realtime/postgres_cdc.ex
- Adds LHR region so we have two regions in the EU (if FRA fails traffic will failover to LHR now which is closer than IAD)
- Adds SJC region so we have two regions in the US
- Uses MAA instead of SIN (network may be better)
- Adds some type specs to functions
Note
- Update regions with `flyctl` after deploy
> chore: add regions

- lib/realtime/api/tenant.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/user_socket.ex
- priv/repo/migrations/20230110180046_add_limits_fields_to_tenants.exs
- test/realtime/extensions/cdc_rls/cdc_rls_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
- Adds `max_channels_per_client`, `max_bytes_per_second` and `max_joins_per_second` to the db
- Updates the `UserSocket` and `RealtimeChannel` to use these db limits
- Updates tests
Notes
- I chose to use an `integer` type for the the `max_bytes_per_second` field so technically the db supports almost 2 gigabytes per second (probably enough) rate limit because of the largest supported integer of `2147483647`
- I'm thinking this will make it easy to call `:erlang.external_size` which returns bytes and we won't have to do any conversion.
- This PR does not implement limiting for `max_bytes_per_second` yet
> feat: add hard coded limits to the db

- config/test.exs
- lib/realtime/repo.ex
- lib/realtime_web/router.ex
Looks like we had a replica we weren't using. Let's use it!
⚠️ Set the env `DB_HOST_REPLICA_SJC` before release ⚠️
> chore: add sjc replica

- .github/workflows/mirror.yml
- .github/workflows/prod.yml
- .github/workflows/prod_linter.yml
- .github/workflows/staging.yml
- .github/workflows/staging_linter.yml
- .github/workflows/staging_supabench.yml
- .releaserc
- config/config.exs
- config/runtime.exs
- config/test.exs
- demo/pages/[...slug].tsx
- lib/extensions/postgres_cdc_rls/cdc_rls.ex
- lib/extensions/postgres_cdc_rls/syn_handler.ex
- lib/realtime/helpers.ex
- lib/realtime/monitoring/prom_ex.ex
- lib/realtime/postgres_cdc.ex
- lib/realtime/repo.ex
- lib/realtime_web/router.ex
- lib/realtime_web/templates/layout/live.html.heex
- mix.exs
> feat: release

- assets/js/app.js
- lib/realtime_web/live/inspector_live/index.html.heex
Shows the database latency on the database events on the inspector.
However, I need subsecond `commit_timestamp`s for it to be accurate.
https://user-images.githubusercontent.com/1019814/213325827-7eab2398-d2ea-4976-a055-7d2d6e22f8a7.mp4
> feat: show latency on db events on inspector

- Dockerfile
- limits.sh
- tailscale/wrapper.sh
Bug fix, feature, docs update, ...
rlimit is always set to 100k, causing problem when ran in docker rootless mode
- uses system default if `RLIMIT_NOFILE` is unset (empty string)
- naming follows linux convention https://man7.org/linux/man-pages/man2/getrlimit.2.html
> fix: make rlimit configurable by env var

- priv/repo/migrations/20230128025114_add_in_op_to_filters.exs
- priv/repo/postgres/migrations/20230128025114_add_in_op_to_filters.exs
- priv/repo/postgres/migrations/20230128025212_enable_filtering_on_delete_record.exs
feature
- Use the `in` op when listening to filters (https://github.com/supabase/walrus/blob/master/sql/walrus_migration_0004_in_op.sql)
- Use filters when listening to delete records (https://github.com/supabase/walrus/blob/master/sql/walrus_migration_0005_delete_old_record_rls.sql)
> feat: add in op for filter and enable filter on delete records

- assets/js/app.js
- lib/realtime_web/live/ping_live.ex
- priv/repo/postgres/migrations/20230119133233_millisecon_precision_for_walrus.exs
- priv/repo/postgres/migrations/20230119133233_millisecond_precision_for_walrus.exs
- `commit_timestamp` from walrus is now high res `2023-01-19T21:57:13.694Z` 
- Previously was `2023-01-19T13:58:43Z`
- Latency for Postgres changes is now accurate in the Inspector
- Latency on Footer matches precision and style as Postgres change latency
> feat: high res commit_timestamp in Postgres change payload

- lib/extensions/postgres_cdc_rls/subscriptions.ex
When the `filter` is `"subject=in.(hidee,ho)"`
- see the [PostgREST syntax](https://postgrest.org/en/stable/api.html#operators)
> feat: support `in` filter when parsing subscription params

- lib/extensions/postgres_cdc_rls/cdc_rls.ex
- lib/extensions/postgres_cdc_stream/cdc_stream.ex
- lib/realtime/postgres_cdc.ex
Sorts region nodes by node name in case the node list order is unstable.
> fix: sort region nodes by node name

- lib/realtime/helpers.ex
> Allow hosts without subdomains

- lib/realtime/application.ex
- lib/realtime/context_cache.ex
- lib/realtime/monitoring/prom_ex/plugins/tenant.ex
- lib/realtime/tenants.ex
- lib/realtime/tenants/cache.ex
- lib/realtime_web/channels/user_socket.ex
- test/realtime/tenants/cache_test.exs
- `Tenants.Cache` module provides read-through cache functionality for any functions in the module
- `Realtime.ContextCache` to easily build caches for other contexts
- Uses `Tenants.Cache` in `Tenant` metrics poller
- Uses `Tenants.Cache` in `UserSocket`
- `Tenants.Cache` ttl is set to expire in 30 seconds
> feat: cache tenants

- lib/extensions/postgres_cdc_rls/replication_poller.ex
- lib/extensions/postgres_cdc_rls/replications.ex
> fix: terminate backend if replication slot is in use

- lib/extensions/postgres_cdc_rls/replication_poller.ex
There are two kinds of `object_in_use` routines I guess:
- `ReplicationSlotAcquireInternal`
- `ReplicationSlotAcquire`
> fix: match all object_in_use routines

- deploy/fly/prod.toml
Deploy this, should fail because we haven't allocated volumes. Then allocate volumes everywhere.
> feat: add fly volumes for prod

- lib/realtime/monitoring/prom_ex/plugins/tenant.ex
> feat: add cluster total connected users to metrics

- .github/workflows/prod.yml
We want to keep our mix version in sync with our releases version:
- This checks to see mix.exs was updated and fails if not.
> feat: action to check if mix.exs was updated

- .github/workflows/prod.yml
- keep the deploy from getting skipped
> fix: don't care if release was published

- .github/workflows/staging_linter.yml
- lib/extensions/postgres_cdc_rls/migrations.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211116024918_create_realtime_subscription_table.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211116045059_create_realtime_check_filters_trigger.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211116050929_create_realtime_quote_wal2json_function.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211116051442_create_realtime_check_equality_op_function.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211116212300_create_realtime_build_prepared_statement_sql_function.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211116213355_create_realtime_cast_function.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211116213934_create_realtime_is_visible_through_filters_function.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211116214523_create_realtime_apply_rls_function.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211122062447_grant_realtime_usage_to_authenticated_role.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211124070109_enable_realtime_apply_rls_function_postgrest_9_compatibility.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211202204204_update_realtime_subscription_check_filters_function_security.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211202204605_update_realtime_build_prepared_statement_sql_function_for_compatibility_with_all_types.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211210212804_enable_generic_subscription_claims.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20211228014915_add_wal_payload_on_errors_in_apply_rls_function.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20220107221237_update_change_timestamp_to_iso_8601_zulu_format.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20220228202821_update_subscription_check_filters_function_dynamic_table_name.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20220312004840_update_apply_rls_function_to_apply_iso_8601.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20220603231003_add_quoted_regtypes_support.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20220603232444_add_output_for_data_less_than_equal_64_bytes_when_payload_too_large.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20220615214548_add_quoted_regtypes_backward_compatibility_support.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20220712093339_recreate_realtime_build_prepared_statement_sql_function.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20220908172859_null_passes_filters_recreate_is_visible_through_filters.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20220916233421_update_apply_rls_function_to_pass_through_delete_events_on_filter.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20230119133233_millisecond_precision_for_walrus.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20230128025114_add_in_op_to_filters.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20230128025212_enable_filtering_on_delete_record.ex
- lib/extensions/postgres_cdc_rls/supervisor.ex
- priv/repo/postgres/migrations/20211122062447_grant_realtime_usage_to_authenticated_role.exs
Bug fix
Running tenant database migrations eats up a lot of memory and causes OOM errors.
Moved the migrations modules to `/lib` where they will be compiled and, on application start, will be loaded once and used by all tenants wishing to run migrations.
This strategy is recommended: https://github.com/elixir-ecto/ecto_sql/issues/152#issuecomment-536772953
> fix: reference versions and modules to run tenant db migrations

- lib/extensions/postgres_cdc_rls/migrations.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20230227211149_update_subscription_check_filters_for_in_filter_non_text_types.ex
Bug fix
`in` filter only works with `text` types
`in` filter only works with `text` and non-`text` types
- Related: https://github.com/supabase/walrus/pull/71
- Fixes: https://github.com/supabase/realtime/issues/491
> fix: update in filter to work with non-text types

- lib/extensions/postgres_cdc_rls/replications.ex
- lib/extensions/postgres_cdc_rls/subscriptions.ex
Bug fix
Polling replication breaks if there's any table names with spaces in the name.
Polling replication filters out table names with spaces so it'll continue working for other valid table names in the publication.
> fix: filter out table names with spaces when polling replication

- lib/realtime_web/channels/realtime_channel.ex
`access_token` interaction RealtimeChannel events are bloating event counts too much.
100 concurrent users connected throughout the whole month would be:
100 connected * 4 events per minute (2 up 2 down) * 60 minutes * 24 hours = 576_000 events per day
RealtimeChannel event count updates:
> fix: don't count access_token socket interaction as an event

- lib/extensions/postgres_cdc_rls/migrations.ex
- lib/extensions/postgres_cdc_rls/repo/migrations/20230308225145_output_full_record_when_unchanged_toast.ex
Bug fix
When a column's record is TOASTed and unchanged, change payload `record` will not include the column.
When a column's record is TOASTed and unchanged, change payload `record` will include the column.
Related:
- https://github.com/supabase/walrus/pull/67
- https://github.com/supabase/supabase-flutter/issues/272
> fix: output full record with columns when unchanged toast

- config/runtime.exs
- deploy/fly/prod.toml
We're getting close to 16k connections on one node when a node in a region is restarted.
This will give us some room for growth.
> feat: support 100k connections

- lib/extensions/postgres_cdc_rls/replication_poller.ex
- lib/realtime/monitoring/prom_ex/plugins/tenant.ex
- mix.exs
> feat: add polling query metric

- lib/realtime/monitoring/prom_ex/plugins/tenant.ex
- mix.exs
- Convert from `:native` doesn't work here use `:microsecond`
> fix: unit conversion for polling query metric

- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
Bug fix
Tenant delete endpoint would return a `503` error, or take a long time, when it fails to stop all the processes related to `PostgresCdc`. 
Tenant delete endpoint deletes the tenant from Realtime database, and then creates an async process to stop all processes, so it'll take at most 15 seconds or so and won't return a `503`.
> fix: only delete tenant from database on tenant delete endpoint

- Makefile
- lib/realtime/monitoring/os_metrics.ex
- mix.exs
- rel/vm.args.eex
Still not getting crash dumps on oom's.
I thought about monitoring `:memsup.get_system_memory_data()` and then using `erlang:halt/1` to trigger a crash dump when memory usage gets low but looking at our metrics memsup doesn't seem to be reporting what our host is reporting for memory usage.
So this attempt consists of:
Now if a process does accumulate a lot of heap it will be killed and we should at least see the error log for it.
> fix: error on memory usage

- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
Clients can send over a new "access_token" which causes us to resubscribe to Postgres. Some clients seem to do this even if the access_token has not changed. With lots of clients connected this can cause extreme thrashing on the realtime.subscription table. 
If the access_token in the socket is the same as the one they are trying to send over, don't do anything.
> fix: token refresh

- lib/realtime_web/endpoint.ex
- mix.exs
- Adds support for Phoenix.Socket.V2.JSONSerializer
Opens up options for people to use more client libraries because more libs are V2 compatible not V1.
> feat: support v2 json serializer

- lib/realtime_web.ex
- mix.exs
This logs handle_in messages as `info` level so now if users connect to the socket with the `log_level=info` param the actual socket messages will be visible in their logs.
> feat: logs handle_in messages as info

- mix.exs
- test/realtime/extensions/cdc_rls/subscriptions_checker_test.exs
Tests for our SubscriptionChecker were flaky because of the way we checked the elements in the array.
Flaky test due to order of lists
> fix: Fixes flaky test on SubscriptionsCheckerTest

- mix.exs
Sets the proper value in mix.exs of Realtime semver
> fix: Sets proper Realtime semver value

- lib/realtime/helpers.ex
- mix.exs
Useful production code that runs ad-hoc added as an helper
> fix: Add rebalance code as an helper

- lib/realtime/api.ex
- mix.exs
- test/realtime/api_test.exs
We lacked tests for one of the functions from Realtime.API. Added said coverage and refactored tests a bit
> fix: Improve coverage of Realtime.API tests

- lib/realtime/tenants.ex
- lib/realtime/tenants/batch_broadcast.ex
- lib/realtime_web/channels/auth/channels_authorization.ex
- lib/realtime_web/controllers/broadcast_controller.ex
- lib/realtime_web/controllers/fallback_controller.ex
- lib/realtime_web/open_api_schemas.ex
- lib/realtime_web/plugs/assign_tenant.ex
- lib/realtime_web/plugs/auth_tenant.ex
- lib/realtime_web/router.ex
- mix.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
- test/realtime_web/controllers/tenant_controller_test.exs
- test/realtime_web/plugs/auth_tenant_test.exs
- test/support/conn_case.ex
Adds a batch broadcast endpoint so users can push multiple messages into multiple topics
New endpoint:
POST `/api` where a user can send:
```
{"messages": [ {"topic": "topic", "payload": "payload"} ]}
```
> feat: Add broadcast endpoint

- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
We always use Presence even if a client doesn't explicitly ask so let's not count this `presence_state` message for now.
> fix: dont count Presence state message

- lib/realtime_web/plugs/auth_tenant.ex
- mix.exs
- test/realtime_web/plugs/auth_tenant_test.exs
Adds support for apikey header for Tenant authorization due to the way we are routing requests in our api gateway
> fix: Support apikey header for Tenant authorization

- lib/realtime_web/api_spec.ex
- mix.exs
Update openapi docs to have tenant as a param of the URL
> fix: Update openapi docs to have tenant as a param of the URL

- mix.exs
- rel/env.sh.eex
Due to the way we're setting up AWS deployment, we need to properly set the node long name.
> chore: Adapt script for AWS to use a IPV6 address

- lib/realtime/application.ex
- lib/realtime/monitoring/erl_sys_mon.ex
- mix.exs
Logs :erlang.system_monitor messages and gets us logs like:
> fix: log :erlang.system_monitor messages

- config/runtime.exs
- config/test.exs
- lib/extensions/postgres_cdc_rls/cdc_rls.ex
- lib/extensions/postgres_cdc_rls/syn_handler.ex
- lib/extensions/postgres_cdc_stream/cdc_stream.ex
- lib/realtime/api.ex
- lib/realtime/application.ex
- lib/realtime/helpers.ex
- lib/realtime/postgres_cdc.ex
- lib/realtime/repo.ex
- lib/realtime/repo_replica.ex
- lib/realtime/tenants.ex
- mix.exs
- tailscale/wrapper.sh
- test/realtime/repo_replica_test.exs
Changes multiple elements to support AWS regions:
* Read replicas now point to the correct server and set the correct module name
* Replica repository is loaded dynamically and only when required to avoid extra modules to be loaded
> fix: Support AWS regions

- mix.exs
- tailscale/wrapper.sh
Only run migration on AWS and use the correct command.
Fly does not need to run migrations (in fact was breaking in staging) and there's already a migration command available
> fix: Only run migration on AWS and use the correct command

- lib/realtime/helpers.ex
- lib/realtime/monitoring/prom_ex.ex
- lib/realtime_web/templates/layout/live.html.heex
- mix.exs
Set id based on host name instead of fly variable
Currently we're using a variable set at the cluster level meaning that we will get repeated metrics for id ending up with the wrong metrics on metrics dashboards
> fix: Set id based on host name instead of fly variable

- config/runtime.exs
- lib/realtime/cluster_strategy/postgres.ex
- mix.exs
- test/realtime/cluster_strategy/postgres_test.exs
Currently we have nodes connecting from different versions which could have a negative impact on the overall cluster operations. To avoid it, we're taking into consideration the version when connecting nodes via libcluster Postgres strategy.
> fix: Take version into consideration in Postgres libcluster Strategy

- config/runtime.exs
- config/test.exs
- lib/realtime/repo_replica.ex
- mix.exs
Adds read replica support if deployed in us-west-1 AWS (San Jose).
> fix: add support for San Jose AWS region

- lib/extensions/postgres_cdc_rls/replication_poller.ex
- lib/realtime/helpers.ex
- mix.exs
- test/realtime/cluster_strategy/postgres_test.exs
Refactor Replication Poller to improve readability
> fix: Refactor Replication Poller to improve readability

- lib/realtime_web/controllers/broadcast_controller.ex
- lib/realtime_web/controllers/fallback_controller.ex
- lib/realtime_web/open_api_schemas.ex
- lib/realtime_web/views/changeset_view.ex
- lib/realtime_web/views/error_view.ex
- mix.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
To prevent over usage by customers, we will take into account the Rate Limits.
We handle two situations:
* The existing batch will trigger a rate limit so we advice to reduce the batch size
* Rate limit has been hit so we can't process the request
> fix: Add Rate limit to Broadcast endpoint

- config/test.exs
- lib/realtime_web/controllers/broadcast_controller.ex
- mix.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
Changes the event payload to match the current channel broadcast logic.
Also reduce test flakiness by adding mocks to Broadcast tests as they were testing the Counters logic without the need for it.
> fix: Change event payload to match current broadcast logic

- lib/realtime/api/tenant.ex
- lib/realtime_web/open_api_schemas.ex
- lib/realtime_web/views/tenant_view.ex
- mix.exs
- test/realtime/extensions/cdc_rls/cdc_rls_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
- test/realtime_web/controllers/tenant_controller_test.exs
feature
Only `max_concurrent_users` is in the response payload when creating, updating, and showing tenant on api request.
`max_channels_per_client`, `max_events_per_second`, and `max_joins_per_second` will now be part of response payload as well.
> feat: expose additional limits for tenant endpoints

- lib/realtime_web/open_api_schemas.ex
- mix.exs
Adds the information that clients will prepend realtime: as their channel and users using this endpoint directly should also do that
> fix: Improve docs on Broadcast endpoint

- lib/realtime/tenants.ex
- lib/realtime/tenants/connect.ex
- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
- test/realtime_web/controllers/tenant_controller_test.exs
Uses the DBConnection pid managed `Tenants.Connect` to establish health
> fix: heath check should check the conn managed by Tenants.Connect

- lib/realtime/tenants/connect.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/tenants/connect_test.exs
To ensure that we limit the amount of connections to a tenant database, we will check if that tenant has any users and if not, we kill the database connection.
> fix: Disconnect when tenant has no users

- config/runtime.exs
- lib/extensions/postgres_cdc_rls/replication_poller.ex
- lib/extensions/postgres_cdc_rls/supervisor.ex
- lib/realtime/application.ex
- mix.exs
- test/realtime/extensions/cdc_rls/replication_poller_test.exs
Sets a default value for slot_name_suffix so we avoid issues during deployments
Plus sets the SynHandler as conflict resolution for :syn on the Application.ex level
> fix - Set slot_name_suffix to avoid conflicts on deploys

- config/runtime.exs
- lib/extensions/postgres_cdc_rls/replication_poller.ex
- mix.exs
- test/realtime/extensions/cdc_rls/replication_poller_test.exs
Mix project isn't available on bootup. Revert to use a env var
> fix: Fix broken runtime.exs

- lib/realtime/repo.ex
- lib/realtime/tenants/migrations.ex
- mix.exs
- test/realtime/repo_test.exs
Checks that we're killing the dynamic repo at the end of it's usage
> fix: Add tests to ensure migrations kill connection upon end

- lib/realtime/api/tenant.ex
- lib/realtime/tenants.ex
- lib/realtime/tenants/connect.ex
- mix.exs
- priv/repo/migrations/20231024094642_add_tenant_suspend_flag.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants_test.exs
Add suspend flag to block new connections to tenant db
> fix: Add suspend flag to block new connections to tenant db

- lib/realtime/helpers.ex
- mix.exs
Add helper to kill all db conns to a given tenant
> fix: Add helper to kill all db conns to a given tenant

- lib/realtime/application.ex
- lib/realtime/tenants.ex
- lib/realtime/tenants/cache.ex
- lib/realtime/tenants/cache_pub_sub_handler.ex
- lib/realtime/tenants/cache_supervisor.ex
- lib/realtime/tenants/connect.ex
- mix.exs
- test/realtime/tenants/cache_supervisor_test.exs
- test/realtime/tenants/cache_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants_test.exs
Handles events of suspending and unsuspending tenants by:
* Broadcasting a operation message to suspend / unsuspend a tenant
* Connect receives said messages and handles them appropriately
* Invalidates Cachex for that tenant
> fix: Handle suspend / unsuspend tenants properly in Connect module

- lib/realtime/helpers.ex
- lib/realtime/tenants/connect.ex
- mix.exs
- test/realtime/tenants/connect_test.exs
Due to the way we were creating connections we kept a lot of Db Connections working that would keep retrying increasing the number of connections per tenant whenever one call would fail.
We now kill the Postgrex pid if we fail to query the database.
> fix: Avoid exponential connection creation

- Dockerfile
- mix.exs
There's a new way to install node. Deprecated way was blocking releases
> fix: Change how we install node in Dockerfile

- lib/realtime/repo.ex
- mix.exs
- test/realtime/repo_test.exs
Using the Repo loader to reduce the code loaded and to properly set the metadata of the created struct
> fix: Reduce code for ecto schema loading

- lib/extensions/postgres_cdc_rls/worker_supervisor.ex
- lib/realtime/tenants/migrations.ex
- mix.exs
* Switched migration to be rest_for_all to avoid migrations from restarting constantly
* Added application_name to migrations to easily debug issues
* Changed backoff strategy on Migrations which will avoid exponential backoff and kill pid on fail
> fix: Improving Migrations error handling

- Dockerfile
- docker-compose.yml
- mix.exs
- tailscale/wrapper.sh
Currently we're not storing the Erlang Crash dumps. This changes allows to trap exist signals, fetch the crash dump and send it to an S3 bucket.
Can be emulated locally by running:
1. `docker compose up`
2. `docker exec -it realtime-server bin/realtime remote`
3. `Process.whereis(:application_controller) |> Process.exit(:kill)`
Use the Minio Console to fetch the crash logs when testing the docker environment. The address is on minio container startup
> fix: Send crash dump to S3 bucket

- lib/realtime/helpers.ex
- lib/realtime/tenants/migrations.ex
- mix.exs
DBConnection seems to not properly link to parent process.
As such, when a parent process dies, the DBConnection pool will be kept alive and keeps retrying to connect potentially creating a big issues of pending processes that keep accumulating.
This change will change the backoff strategy to `:stop` and let the parent process do the retrying
> fix: Change backoff type to stop connection

- lib/realtime/channels.ex
- lib/realtime/repo.ex
- lib/realtime_web/controllers/channels_controller.ex
- mix.exs
- test/realtime/channels_test.exs
- test/realtime/repo_test.exs
- test/realtime_web/controllers/channels_controller_test.exs
Add Update endpoint and required Repo changes
> fix: Add Update endpoint and required Repo changes

- demo/package-lock.json
fix demo dep vulnerability
resolves https://github.com/supabase/realtime/security/dependabot/25
> fix: version bump postcss to 8.4.32 to fix vulnerability

- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
We should check the rate limits of the user before doing the more demanding check on Connection status.
> fix: Check rate limits before checking connection

- lib/extensions/postgres_cdc_rls/cdc_rls.ex
- lib/extensions/postgres_cdc_rls/subscriptions_checker.ex
- lib/extensions/postgres_cdc_stream/cdc_stream.ex
- lib/realtime/helpers.ex
- lib/realtime/monitoring/latency.ex
- lib/realtime/rpc.ex
- lib/realtime/tenants/connect.ex
- lib/realtime_web/controllers/metrics_controller.ex
- mix.exs
Abstracts the RPC calls so we can add instrumentation around it. Only sends the time taken to run the rpc call. On timeout returns max value
> fix: Instrument RPC calls

- README.md
- config/runtime.exs
- mix.exs
Bug fix for https://github.com/supabase/realtime/issues/761:
- introduces a new environment variable `MAX_HEADER_LENGTH` that can be used to override config -> http -> protocol_options -> max_header_value_length from its default value in Elixr (4096)
- If no value is set, the Elixr default of 4096 will continue to be used
- updates README to reflect these changes
With SSR and the use of cookies to authenticate on the server, all cookies need to be sent to Supabase requests, including Realtime. If these cookies exceed the (rather low) default of 4096 (which, with an auth provider for supabase, can happen extremely easily), realtime subscriptions fail with a 431 error. 
Edit: we are using Keycloak as our Supabase authentication provider, and it looks like Keycloak is a bit notorious for …
> fix: override `max_header_value_length` using environment variable

- lib/extensions/postgres_cdc_rls/subscription_manager.ex
- mix.exs
> fix: calls fetch_publication_tables on init

- lib/realtime/helpers.ex
- mix.exs
Configurable backoff strategy for DBConnection
> fix: Configurable backoff strategy for DBConnection

- lib/realtime/api/channel.ex
- lib/realtime/repo.ex
- lib/realtime/tenants/authorization.ex
- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20240108234812_add_channels_column_for_write_check.ex
- lib/realtime/tenants/repo/migrations/20240109165339_add_update_grant_to_channels.ex
- lib/realtime_web/plugs/rls_authorization.ex
- mix.exs
- test/realtime/repo_test.exs
- test/realtime/tenants/authorization_test.exs
- test/support/data_case.ex
Add write permissions checks for the Authorization modules.
It checks if a given user can write by trying to updating a column in the channels table. After done, reverts the change within the same transaction.
Also took the time to refactor a bit the code to use some helper functions previously built in the Repo module to avoid bare sql code and have a more structured approach.
> fix: Add write checks to channels

- lib/realtime/helpers.ex
- mix.exs
Fixes bug where inet (IP V4) was being used instead of inet6 (IP V6) due to badly set connection configuration.
> fix: Use inet6 when host requires it

- lib/realtime/helpers.ex
- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
- test/realtime/helpers_test.exs
- test/realtime_web/controllers/tenant_controller_test.exs
On tenant delete, remove replication slots
> fix: On tenant delete, remove replication slots

- lib/extensions/postgres_cdc_rls/replication_poller.ex
- lib/extensions/postgres_cdc_rls/subscription_manager.ex
- lib/extensions/postgres_cdc_rls/subscriptions_checker.ex
- lib/extensions/postgres_cdc_stream/replication.ex
- lib/realtime/helpers.ex
- lib/realtime/tenants/migrations.ex
- mix.exs
- test/realtime/helpers_test.exs
We only use socket opts to set ipv4 or ipv6 as such we move that logic into the connect_db code to prevent old state from impacting connect_db logic.
> fix: Move socket opts to connect

- lib/extensions/postgres_cdc_rls/subscriptions_checker.ex
- lib/realtime/monitoring/prom_ex/plugins/tenant.ex
- lib/realtime/monitoring/prom_ex/plugins/tenants.ex
- mix.exs
- test/realtime/extensions/cdc_rls/subscriptions_checker_test.exs
- test/realtime/helpers_test.exs
Currently logs were leading users to be concerned with their Realtime status when that does not reflect anything of concern since it's part of the normal flow of Realtime to remove phantom subscriptions and cleanup inactive pids from ETS.
As such we're moving this information from Logs to Telemetry so we avoid concerning our users but keep track of happens with the subscription table.
> fix: Move from Logs to Telemetry on Subscription checks

- lib/realtime/helpers.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/realtime_channel/broadcast_handler.ex
- lib/realtime_web/channels/realtime_channel/presence_handler.ex
- lib/realtime_web/router.ex
- mix.exs
- test/realtime_web/controllers/channels_controller_test.exs
In preparation to add Authorization, we're separating concerns out of the module RealtimeChannel which had most of the logic within the same module.
This will make it easier to extend the Broadcast and Presence features.
We're also moving the Channels endpoints to a v3 route
> fix: Refactor Realtime Channel

- lib/extensions/postgres_cdc_rls/subscriptions_checker.ex
- lib/realtime/telemetry/telemetry.ex
- mix.exs
Change measures to maps to avoid deprecation warnings
> fix: Change measures to maps to avoid deprecation warnings

- lib/extensions/postgres_cdc_rls/worker_supervisor.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/migrations.ex
- mix.exs
- test/realtime/channels_test.exs
- test/realtime/repo_test.exs
- test/realtime/tenants/authorization_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime_web/controllers/channels_controller_test.exs
- test/realtime_web/controllers/tenant_controller_test.exs
- test/realtime_web/plugs/rls_authorization_test.exs
Running migrations on Connect will ensure that the tenant database will have the required tables for the new Realtime features. Plus it offloads this concern from the extensions and moves it to the Tenant domain of concerns.
> fix: Run migrations on Connect

- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
- test/realtime_web/controllers/tenant_controller_test.exs
Invalidates Tenant Cache on delete.
This needs to be done because if the client connects within the range of normal cache invalidation they will end up creating replication slot which will leave the database with a replication slot that will not be used and potentially block maintenance operations.
> fix: Invalidate Cache on delete

- lib/realtime/tenants.ex
- lib/realtime/tenants/cache.ex
- lib/realtime/tenants/cache_pub_sub_handler.ex
- lib/realtime/tenants/cache_supervisor.ex
- lib/realtime/tenants/connect.ex
- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
- test/realtime/tenants/cache_supervisor_test.exs
- test/realtime/tenants/cache_test.exs
- test/realtime/tenants_test.exs
Creates a new method to emit a cache invalidation message to all connected nodes. Also using it in the delete action of Tenant Controller since this could create issues with replication_slots
> fix: Distributed Tenant Cache invalidation

- lib/extensions/postgres_cdc_rls/cdc_rls.ex
- lib/extensions/postgres_cdc_stream/cdc_stream.ex
- lib/realtime/postgres_cdc.ex
- lib/realtime/tenants/cache.ex
- lib/realtime/tenants/connect.ex
- lib/realtime_web/controllers/tenant_controller.ex
- lib/realtime_web/open_api_schemas.ex
- mix.exs
- test/realtime_web/controllers/tenant_controller_test.exs
> fix: make tenant delete more robust

- lib/extensions/postgres_cdc_rls/cdc_rls.ex
- lib/extensions/postgres_cdc_stream/cdc_stream.ex
- lib/realtime/api.ex
- lib/realtime/postgres_cdc.ex
- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
> fix: use primary sometimes

- lib/extensions/postgres_cdc_rls/cdc_rls.ex
- lib/extensions/postgres_cdc_rls/worker_supervisor.ex
- lib/extensions/postgres_cdc_stream/cdc_stream.ex
- lib/extensions/postgres_cdc_stream/worker_supervisor.ex
- mix.exs
Tenant primary check must be in Extension inits because otherwise lots of db calls could happen when many clients connect at once, before syn has distributed process to the whole cluster.
Moving this check to the init ensures db is only called once per tenant when starting Extension supervision tree on only one node.
> fix: move tenant primary check

- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
- test/realtime_web/controllers/tenant_controller_test.exs
As deletion is an idempotent operation, we do not require the endpoint to return "not found" status code and we will move to a "accept" status code.
> fix: Delete endpoint returns accept response

- .github/workflows/staging_linter.yml
- lib/realtime/channels.ex
- lib/realtime/repo.ex
- lib/realtime/tenants/authorization.ex
- lib/realtime/tenants/authorization/permissions/broadcast_policies.ex
- lib/realtime/tenants/authorization/permissions/channel_policies.ex
- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20240311171622_add_insert_and_delete_grant_to_channels.ex
- lib/realtime_web/controllers/channels_controller.ex
- lib/realtime_web/controllers/fallback_controller.ex
- lib/realtime_web/plugs/rls_authorization.ex
- lib/realtime_web/router.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/channels/cache_test.exs
- test/realtime/channels_test.exs
- test/realtime/repo_test.exs
- test/realtime/tenants/authorization/permissions/broadcast_policies_test.exs
- test/realtime/tenants/authorization/permissions/channel_policies_test.exs
- test/realtime/tenants/authorization_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime_web/controllers/channels_controller_test.exs
- test/realtime_web/plugs/rls_authorization_test.exs
- test/support/data_case.ex
- test/support/generators.ex
- test/support/tenant_connection.ex
To support API use case and SDK support we need to implement the required policies.
This adds a new Policy to ChannelPolicy that defines:
* If a channel name is in the request body of a post request, we add it to the authorization context
* If the user is able to Create a channel fully and Delete it fully we set it to write true
This will be used by the controller for the create and delete flows. Update flow already had a check since we are able to load a channel and the permissions will be more fine grained to that channel
> fix: Add proper policies around Channel Controller

- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/realtime_channel/broadcast_handler.ex
- mix.exs
- test/integration/rt_channel_test.exs
To facilitate the usage of Authz in Realtime during this first iteration we will have the assumption that if we have a Channel present in the tenant database we will have the assumption that the user intented to have a private channel which will end calculating the policies based on RLS rules.
Also small fix for counter which was counting failed sent messages
> fix: Infer private channel based on Channel entry

- lib/realtime/channels.ex
- lib/realtime_web/controllers/channels_controller.ex
- lib/realtime_web/plugs/rls_authorization.ex
- lib/realtime_web/router.ex
- mix.exs
- test/realtime/channels_test.exs
- test/realtime_web/controllers/channels_controller_test.exs
- test/realtime_web/plugs/rls_authorization_test.exs
To make the API easier to interact with, we're using name instead of using id to run CRUD operations on channels
> fix: Change param from id to name in Channel CRUD actions

- lib/realtime/channels.ex
- lib/realtime/helpers.ex
- lib/realtime/tenants/authorization.ex
- lib/realtime/tenants/connect.ex
- mix.exs
- test/realtime/tenants/authorization/permissions/channel_policies_test.exs
Postgrex is unable to checkout connections from external nodes (as expected...) so we need to run an rpc call against the db connection owner instead.
This abstracts that work by giving that work to the Connect module which already is the one attributing said connections.
> fix: Run Query within transaction of DB Conn owner

- lib/realtime_web/channels/realtime_channel/presence_handler.ex
- mix.exs
Presence was throwing two messages for the same user because we were updating presence two times leading to a duplicate message.
Before: 
After:
> fix: Handle double message on Presence connect

- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20240401105812_create_realtime_admin_and_move_ownership.ex
- mix.exs
Creates a new role called `supabase_realtime_admin`, moves ownership to this role and then we grant all the attributes roles to postgres user so users can add RLS rules to realtime tables
> fix: Posgtres role with Realtime Admin grants

- bench/secrets.exs
- lib/realtime/api/tenant.ex
- lib/realtime_web/channels/auth/channels_authorization.ex
- lib/realtime_web/channels/auth/jwt_verification.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/realtime_channel/assign.ex
- lib/realtime_web/channels/user_socket.ex
- lib/realtime_web/open_api_schemas.ex
- lib/realtime_web/plugs/auth_tenant.ex
- lib/realtime_web/router.ex
- mix.exs
- priv/repo/migrations/20240306114423_add_tenant_jwt_jwks.exs
- test/api_jwt_secret_test.exs
- test/realtime/extensions/cdc_rls/cdc_rls_test.exs
- test/realtime_web/channels/auth/channels_authorization_test.exs
- test/realtime_web/channels/auth/jwt_verification_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
- test/realtime_web/controllers/metrics_controller_test.exs
- test/realtime_web/controllers/tenant_controller_test.exs
- test/support/generators.ex
Adds support for verifying end-user JWTs using JWKS in addition to the JWT secret. This means that third-party authentication systems that use asymmetric JWTs can be used with Realtime.
> feat: add jwks support

- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
Matching error due to not returning socket on ignored message
> fix: Matching error due to not returning socket on ignored message

- lib/realtime/tenants.ex
- mix.exs
- test/realtime_web/controllers/tenant_controller_test.exs
To ensure users have all required elements to work with Realtime we will start running migrations on the healthcheck.
We chose this approach to be sure that the database is already available when Realtime is checked.
> fix: Migrate on Healthcheck

- lib/realtime/tenants.ex
- mix.exs
- test/realtime_web/controllers/tenant_controller_test.exs
Run migration query in the correct region
> fix: Run migration query in the correct region

- lib/realtime_web/controllers/broadcast_controller.ex
- mix.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
On non authorization required channels we avoid policies. 
On authorization required channels we will run policies within a single transaction to reduce the amount of connections taken for the operation
> fix: Broadcast Endpoint performance improvement

- lib/realtime/helpers.ex
- mix.exs
Configurable pool size and queue target per tenant on Connect
> fix: Configurable pool size and queue target per tenant on Connect

- lib/realtime_web/controllers/channels_controller.ex
- mix.exs
- test/realtime_web/controllers/channels_controller_test.exs
* Listing without required authentication will return an empty list
* All other commands will return 404 on lack of authentication
> fix: Improve returns of Channel endpoint

- lib/realtime/tenants.ex
- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/realtime/tenants_test.exs
To avoid cross communication between public and private channels we will add a prefix on private channels which is determined by checking if a channel exists in realtime.channel with a given name.
> fix: Add prefix on secure channels

- lib/realtime_web/channels/realtime_channel/presence_handler.ex
- mix.exs
Bug fix
`Presence.track/4` returns `:error` on successful tracking.
`Presence.track/4` returns `:ok` on successful tracking.
Related: https://github.com/supabase/realtime-js/pull/290
> fix: return :ok on successful Presence.track/4 call

- lib/realtime/helpers.ex
- mix.exs
Revert default poolsize for checker to 1
> fix: Revert default poolsize for checker to 1

- lib/extensions/postgres_cdc_rls/cdc_rls.ex
- lib/realtime/helpers.ex
- mix.exs
- we had db_pool size of 5 but small dbs were running out of connections
- db_pool size of 1 is a bit too small and causes 5xx's on Broadcast POST
- change db_pool size to 3
- change subscribers_pool_size from 5 to 3 so total Realtime conns remains the same
- 3 should be fine
- if this is too small we will see query timeouts on `Extensions.PostgresCdcRls.Subscriptions.create` calls
- will keep us at 9 total connections
Previously connections looked like:
| usename        | application_name                  |
| -------------- | --------------------------------- |
| supabase_admin | realtime_subscription_manager_pub |
| supabase_admin | realtime_subscription_manager_pub |
| supabase_admin | realtime_subscription_manager_pub |
| supabase_admin | realtime_subscription_manager_pub |
| …
> fix: tune connections a bit more

- lib/realtime/api/broadcast.ex
- lib/realtime/api/channel.ex
- lib/realtime/api/presence.ex
- lib/realtime/tenants/authorization/policies/broadcast_policies.ex
- lib/realtime/tenants/authorization/policies/channel_policies.ex
- lib/realtime/tenants/authorization/policies/presence_policies.ex
- mix.exs
- test/realtime/tenants/authorization/permissions/broadcast_policies_test.exs
- test/realtime/tenants/authorization/permissions/channel_policies_test.exs
- test/realtime/tenants/authorization/permissions/presence_policies_test.exs
Uses the `updated_at` column to generate Channel policies instead of `check` column.
We want to drop the `check` column as it'll likely be confusing for folks.
> fix: use updated_at column to check RLS policy instead

- lib/realtime/tenants.ex
- mix.exs
Avoid migration when possible on healthcheck
> fix: Avoid migration when possible on healthcheck

- lib/realtime/api/tenant.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/controllers/broadcast_controller.ex
- mix.exs
- priv/repo/migrations/20240418082835_add_authorization_flag.exs
- priv/repo/seeds_after_migration.exs
- test/support/generators.ex
Add flag to enable / disable Authorization
> fix: Add flag to enable / disable Authorization

- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/integration/rt_channel_test.exs
Lack of permissions on Presence will no longer lock the user out of the Channel.
> fix: Presence policies properly applied

- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
Avoid calls properly on tenant flag
> fix: Avoid calls properly on tenant flag

- lib/realtime_web/plugs/auth_tenant.ex
- mix.exs
- test/realtime_web/plugs/auth_tenant_test.exs
Bearer prefix at the moment was case sensitive which could be a problem with some clients.
> fix: Case insensitive Bearer prefix

- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/integration/rt_channel_test.exs
Receiving Broadcasts was wrongly requiring write permissions.
> fix: Receiving Broadcast required write instead of read

- lib/realtime/monitoring/prom_ex/plugins/tenants.ex
- lib/realtime/rpc.ex
- mix.exs
RPC metrics are very consuming per tenant. We're moving towards a more global RPC check approach which will reduce the metrics endpoint reply as a consequence.
> fix: Reduce Metrics Payload

- lib/extensions/postgres_cdc_rls/cdc_rls.ex
- lib/realtime/database.ex
- lib/realtime/tenants/repo/migrations/20211116024918_create_realtime_subscription_table.ex
- lib/realtime/tenants/repo/migrations/20211116212300_create_realtime_build_prepared_statement_sql_function.ex
- lib/realtime/tenants/repo/migrations/20211116214523_create_realtime_apply_rls_function.ex
- lib/realtime/tenants/repo/migrations/20220603231003_add_quoted_regtypes_support.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/realtime_channel/presence_handler.ex
- mix.exs
- test/integration/rt_channel_test.exs
* Presence had a bad check when tracking changes
* JWT checking had a bad check and a broken test
* Fixed some migrations to be less susceptible to errors on migrations
* Added one connection to db_pool
* Removed one connection from subcriber_pool_size
> fix: Fix improper policy checking

- lib/realtime/api/tenant.ex
- lib/realtime/application.ex
- lib/realtime/database.ex
- lib/realtime/tenants/batch_broadcast.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/listen.ex
- lib/realtime_web/controllers/broadcast_controller.ex
- mix.exs
- priv/repo/migrations/20240704172020_add-notify-private-alpha.exs
- priv/repo/seeds.exs
- test/integration/rt_channel_test.exs
- test/realtime/messages_test.exs
- test/realtime/repo_test.exs
- test/realtime/tenants/authorization/permissions/broadcast_policies_test.exs
- test/realtime/tenants/authorization_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants/listen_test.exs
- test/support/channel_case.ex
- test/support/conn_case.ex
- test/support/data_case.ex
- test/support/generators.ex
- test/support/tenant_connection.ex
Support LISTEN/NOTIFY on `realtime:broadcast` which allows users to trigger broadcast messages by sending a payload to this topic.
```sql
select pg_notify(
'realtime:broadcast',
json_build_object(
'private', $1::boolean,
'topic', $2::text,
'event', $3::text,
'payload', $4::jsonb
)::text
);
```
We want to keep it as close to the Broadcast endpoint as possible and it already includes the feature flag `notify_private_alpha` to enabled it (defaults to false)
> feat: Support LISTEN broadcast in Realtime

- README.md
- lib/realtime/application.ex
- lib/realtime/tenants/listen.ex
- mix.exs
* Currently the way we're doing Listen is too restrictive which is bad when we're using the auto_reconnect option as that will return a tuple {:eventually, #ref{}} reply which creates an exception.
* Add proper shutdown method by doing unlisten when needed
* Log errors properly
* We were not setting db user properly
> fix: Multiple issues on the Listen module

- lib/realtime/tenants/batch_broadcast.ex
- lib/realtime/tenants/listen.ex
- mix.exs
Starts the rate limit for a given tenant on Listen. Also improved logging as it was missing context.
> fix: Start rate limits if not created on Listen

- lib/realtime_web/plugs/auth_tenant.ex
- mix.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
- sets logger metadata earlier
- sends response when unauthorized
- adds a test
> fix: send unauthorized response

- lib/realtime/application.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/migrations.ex
- mix.exs
- test/realtime/tenants/migrations_test.exs
By creating a unique process per host we ensure that we don't have multiple migrations running against the tenant database. We use the encrypted host as the uniqueness key.
> fix: Ensure that only one migration is ran by host

- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20240801235015_unlogged_messages_table.ex
- mix.exs
Due to the way we're doing the checks, to increase performance, we're moving thist able to unlogged.
At a later stage we might revert this and do other approaches but at the moment this is a sane approach
> fix: Set realtime.messages to unlogged

- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20240805133720_logged_messages_table.ex
- mix.exs
Use logged tables for realtime.messages
> fix: Use logged tables for realtime.messages

- lib/realtime/rpc.ex
- mix.exs
Avoid catch to return nested tuple error
> fix: Avoid catch to return nested tuple error

- .gitignore
- lib/realtime_web.ex
- mix.exs
- priv/static/worker.js
To support a future change in the realtime-js library we're adding a static asset to realtime so users can use it as their default worker.
> fix: Add static asset to be used by Web Workers

- lib/realtime_web/channels/auth/channels_authorization.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/user_socket.ex
- mix.exs
- test/realtime_web/channels/auth/channels_authorization_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
- test/support/generators.ex
Improve invalid JWT logs by informing the user of:
* missing claims of the JWT token provided
* inform with claim as a unexpected value
> fix: Improve invalid JWT logs

- mix.exs
- rel/vm.args.eex
Disabling busy wait as it's potentially holding CPU resources unnecessarily and showing increased load in metrics
Read more here:
https://www.erlang.org/doc/apps/erts/erl_cmd.html
https://www.rabbitmq.com/docs/runtime#busy-waiting
> fix: Disable busy wait

- lib/realtime_web/controllers/page_controller.ex
- lib/realtime_web/router.ex
- mix.exs
Adds a new healtcheck for infrastructure to check the status of the service with less impact to the system.
The current healtcheck actually goes through a LiveView which could be impactful.
> fix: Add new healthcheck for infrastructure

- lib/realtime/operations.ex
- lib/realtime_web/dashboard/process_dump.ex
- lib/realtime_web/router.ex
- mix.exs
Add new view to fetch process dumps
> fix: Add new view to fetch process dumps

- lib/realtime/database.ex
- lib/realtime/operations.ex
- mix.exs
Use proper RPC timeouts as this situations can still create some undesirable RPC errors calls and clash with Postgrex connection issues.
> fix: Use proper RPC timeouts

- lib/realtime/tenants.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20211116024918_create_realtime_subscription_table.ex
- lib/realtime/tenants/repo/migrations/20240523004032_redefine_authorization_tables.ex
- lib/realtime/tenants/repo/migrations/20240801235015_unlogged_messages_table.ex
- lib/realtime/tenants/repo/migrations/20240805133720_logged_messages_table.ex
- mix.exs
- test/realtime/tenants/migrations_test.exs
Currently we have migrations that are breaking for certain users, this improves the resiliency of said migrations. We also comment out the unlogged/logged as that is redudant
Also adds context to the logs when running migrations as those were missing at the moment.
> fix: Improve migration resiliency

- lib/realtime/broadcast_changes/handler.ex
- mix.exs
Handle SSL and IP Version on Broadcast Changes
> fix: Handle SSL and IP Version on Broadcast Changes

- lib/realtime/api/message.ex
- lib/realtime/broadcast_changes/handler.ex
- mix.exs
Use UUID for message identifiers
> fix: Use UUID for message identifiers

- lib/realtime/tenants/connect.ex
- mix.exs
- test/realtime/broadcast_changes/handler_test.exs
Trying to stop process that is dead leads to error => `** (stop) exited in: GenServer.stop(#PID<0.43330.0>, :normal, 500)`
handle_continue does not shutdown properly => `** (stop) bad return value: {:stop, :shutdown}`
> fix: Properly handle error on handle_continue

- lib/extensions/postgres_cdc_rls/cdc_rls.ex
- lib/extensions/postgres_cdc_stream/cdc_stream.ex
- lib/realtime/tenants/connect.ex
- mix.exs
- Connect process should start on the same partition for a `tenant_id` now
- Found in CdcRls and CdcStream too
> fix: partition Connect DynamicSupervisors correctly

- lib/realtime/messages.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/connect/create_partitions.ex
- lib/realtime/tenants/janitor.ex
- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20241030150047_messages_partitioning.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/messages_test.exs
- test/support/generators.ex
Adds logic to partition the realtime.messages table. The current way works as follows:
* new table is created called realtime.messages_new that is partitioned by `inserted_at`
* migrate existing policies from realtime.messages to realtime.messages_new
* drop existing realtime.messages table
* rename realtime.messages_new to realtime.messages
* Assign the existing ID sequence to the new table
* Provide all required Grants
* On tenant connect, create dynamically 3 partitions: one for yesterday, tomorrow and today
Everything else works as expected and no changes were required.
> fix: Add partitioning to realtime.messages

- lib/realtime/broadcast_changes/handler.ex
- lib/realtime/database.ex
- mix.exs
Removes warning by not verifying peer certificate. Removes ssl_opts based on Postgrex starting opts https://hexdocs.pm/postgrex/Postgrex.html#t:start_option/0
> fix: Stop SSL warning

- lib/realtime/application.ex
- lib/realtime/tenants.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/janitor.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants/janitor_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
- test/support/data_case.ex
Current implementation was using a more complex query that would load RDS too much. This approach focuses on using ETS and it will determine which databases with the following flow:
* On Connect, tenant will be registered in ETS as active with {tenant.external_id, DateTime.utc_now()}
* Janitor periodically will fetch the ETS entries, chunk them and run a cleanup
* On each tenant cleanup, we will untrack the user by deleting their entry from ETS
> fix: Janitor set to use ETS to reduce load on Database

- lib/realtime/tenants.ex
- lib/realtime/tenants/connect/migrations.ex
- lib/realtime/tenants/migrations.ex
- mix.exs
- test/realtime/tenants/connect_test.exs
Run migrations only when necessary
> fix: Run migrations only when necessary

- mix.exs
Match elixir version with deployment
> fix: Match elixir version with deployment

- lib/realtime/tenants/connect.ex
- mix.exs
add back sleep on connect initialization
> fix: add back sleep on connect initialization

- lib/realtime/tenants/migrations.ex
- mix.exs
Currently postgrex was trying to call a pid that was from another node which is not capable to do. We need to wrap it around Realtime.Database.transaction to run the erpc call against the target node
> fix: Healthcheck improperly calling postgrex

- README.md
- lib/realtime/tenants/migrations.ex
- mix.exs
- test/realtime/tenants/connect_test.exs
- test/realtime_web/controllers/tenant_controller_test.exs
Add better logging around maybe_migrate
> fix: Add better logging around maybe_migrate

- lib/realtime/application.ex
- lib/realtime/tenants.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/janitor.ex
- mix.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants/janitor_test.exs
- test/support/data_case.ex
* we will use the existing syn scope of the Connect module to check which users still have database connections active
* remove ets as this is no longer required
* Janitor will also tackle creating partitions
> fix: Change when we track and create partitions

- lib/realtime/database.ex
- mix.exs
- test/realtime/database_test.exs
- test/realtime/tenants/janitor_test.exs
Handle properly erpc calls on Database.transaction/4
> fix: Handle properly erpc calls on Database.transaction/4

- README.md
- lib/realtime/signal_handler.ex
- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/integration/rt_channel_test.exs
Improve error handling to avoid UnknownErrors. Check README.md changes to see new errors
> fix: Improve error handling to avoid UnknownErrors

- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20241121104152_fix_send_function_.ex
- mix.exs
`realtime` schema prefix not set in send function
> fix: realtime schema prefix not set in send function

- lib/realtime/monitoring/prom_ex.ex
- mix.exs
Add ecto to prometheus metrics
> fix: Add ecto to prometheus metrics

- lib/extensions/postgres_cdc_rls/replication_poller.ex
- lib/realtime/database.ex
- mix.exs
Fetch correct pool value from settings by application name but also allows overrides
> fix: fetch correct pool value from settings by application name

- lib/realtime/database.ex
- mix.exs
Connection pool for realtime_rls was not set properly and was using a higher value than it should leading to Realtime attempting to re-use replication slots creating issues upon connecting to listen to changes
Now we will set `realtime_rls` and `realtime_broadcast_changes` to hardcoded `1` and `realtime_migrations` to hardcoded `2`
> fix: set proper size for realtime_rls pool

- lib/extensions/postgres_cdc_rls/worker_supervisor.ex
- lib/extensions/postgres_cdc_stream/replication.ex
- lib/extensions/postgres_cdc_stream/worker_supervisor.ex
- lib/realtime/gen_counter/gen_counter.ex
- lib/realtime/rate_counter/rate_counter.ex
- lib/realtime/tenants/connect.ex
- lib/realtime_web/plugs/assign_tenant.ex
- mix.exs
- test/e2e/tests.ts
- test/realtime/database_test.exs
- test/realtime/gen_counter/gen_counter_test.exs
- test/realtime/rate_counter/rate_counter_test.exs
* Handles match error on GenCounter in a more grafecul way
* Adds Logger metadata on multiple processes
> fix: Prevent match error on GenCounter

- config/runtime.exs
- mix.exs
> fix: allow IPv6 for DB_HOST

- config/runtime.exs
- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20241220035512_fix_send_function_partition_creation.ex
- mix.exs
The current approach can lead to some unexpected errors due to the multiple calls to NOW() during the creation and checking of partitions
> fix: Improve partition creation on realtime.send

- lib/realtime/application.ex
- lib/realtime/tenants/broadcast_changes/handler.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/listen.ex
- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20241220123912_realtime_send_handle_exceptions_remove_partition_creation.ex
- mix.exs
- test/e2e/tests.ts
- test/realtime/tenants/broadcast_changes/handler_test.exs
- test/realtime/tenants/listen_test.exs
- test/support/tenant_connection.ex
* Adds Realtime.Tenants.Listen to receive error messages from functions so we can better inform our users
* Changes send function to not handle any partition creation
* Changes send function to pg_notify to `realtime:system` so we can capture and handle in Realtime
> fix: listen on notifications for error handling

- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20241224161212_realtime_send_sets_config.ex
- mix.exs
- test/e2e/README.md
- test/e2e/tests.ts
`realtime.send` sets the proper value for realtime.topic so RLS policies are applied properly.
> fix: realtime.send sets the proper value for realtime.topic

- README.md
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/listen.ex
- mix.exs
- test/e2e/README.md
- test/e2e/tests.ts
Make notification connection sync on connect fixing:
```
"MigrationsFailedToRun: {:error,
{:error,
{{:badmatch, {:eventually, #Reference<0.3789860767.1689255938.13723>}},
[
{Postgrex.Notifications, :listen!, 3,
[file: ~c\"lib/postgrex/notifications.ex\", line: 163]},
{Realtime.Tenants.Listen, :init, 1,
[file: ~c\"lib/realtime/tenants/listen.ex\", line: 51]},
{:gen_server, :init_it, 2, [file: ~c\"gen_server.erl\", line: 2229]},
{:gen_server, :init_it, 6, [file: ~c\"gen_server.erl\", line: 2184]},
{:proc_lib, :init_p_do_apply, 3, [file: ~c\"proc_lib.erl\", line: 329]}
]}}}"
```
> fix: Make notification connection sync on connect

- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20250107150512_realtime_subscription_unlogged.ex
- mix.exs
The information we store in realtime.subscripition it's not intended to be long lived so we can reduce the impact on WAL by making this table unlogged
> fix: Change realtime.subcription to be unlogged

- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20250107150512_realtime_subscription_unlogged.ex
- lib/realtime/tenants/repo/migrations/20250110162412_realtime_subscription_logged.ex
- mix.exs
Due to incompatability with PG14, namely the lack of unlogged sequences, we need to revert back to a logged table for realtime.subcription.
> fix: Make realtime.subscription logged

- lib/realtime/api/tenant.ex
- lib/realtime/tenants.ex
- lib/realtime/tenants/batch_broadcast.ex
- lib/realtime/tenants/connect.ex
- mix.exs
- priv/repo/seeds.exs
- priv/repo/seeds_after_migration.exs
- test/integration/rt_channel_test.exs
- test/realtime/database_test.exs
- test/realtime/messages_test.exs
- test/realtime/rate_counter/rate_counter_test.exs
- test/realtime/repo_test.exs
- test/realtime/rpc_test.exs
- test/realtime/tenants/authorization_test.exs
- test/realtime/tenants/cache_supervisor_test.exs
- test/realtime/tenants/cache_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants/janitor_test.exs
- test/realtime/tenants/listen_test.exs
- test/realtime/tenants/migrations_test.exs
- test/realtime/tenants/replication_connection_test.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
- test/realtime_web/controllers/tenant_controller_test.exs
- test/support/cleanup.ex
- test/support/generators.ex
Database Broadcast enabled for all users by removing the feature flag.
> feat: Database Broadcast enabled

- lib/realtime/tenants/replication_connection.ex
- mix.exs
- test/realtime_web/controllers/tenant_controller_test.exs
To make it easier to manage supabase specific elements we're adding the prefix supabase to the replication slot and publication
> fix: Prefix replication slot and publication name

- lib/realtime/database.ex
- lib/realtime/rpc.ex
- lib/realtime/tenants/authorization.ex
- lib/realtime/tenants/authorization/policies/broadcast_policies.ex
- lib/realtime/tenants/authorization/policies/presence_policies.ex
- lib/realtime/tenants/batch_broadcast.ex
- lib/realtime/tenants/connect.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/realtime_channel/broadcast_handler.ex
- lib/realtime_web/channels/realtime_channel/presence_handler.ex
- mix.exs
- test/realtime/database_test.exs
- test/realtime/tenants/authorization_test.exs
* Separates read and write flows for authorization to ensure we are able to only check writes when user tries to broadcast or track presence
* Adds telemetry to Database.transaction so we can check latency of queries
* Add latency on Authorization queries
> fix: Separate read and write authorization and add telemetry

- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/realtime_channel/presence_handler.ex
- mix.exs
Presence handler reduce authorization validations
> fix: Presence handler reduce authorization validations

- lib/realtime/monitoring/prom_ex/plugins/tenants.ex
- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/replication_connection.ex
- lib/realtime/tenants/repo/migrations/20250123174212_remove_unused_publications.ex
- mix.exs
Set fixed publication name; cleanup unused publications
> fix: Set fixed publication name; cleanup unused publications

- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/integration/rt_channel_test.exs
Match error on handle_info when token is checked for exp
> fix: Match error on handle_info when token is checked for exp

- README.md
- config/config.exs
- config/test.exs
- lib/extensions/postgres_cdc_rls/subscriptions.ex
- lib/realtime/logs.ex
- lib/realtime/tenants/authorization.ex
- lib/realtime/tenants/migrations.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/realtime_channel/broadcast_handler.ex
- lib/realtime_web/channels/realtime_channel/logging.ex
- lib/realtime_web/channels/user_socket.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/tenants/authorization_test.exs
- test/realtime_web/channels/realtime_channel/logging_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
- test/support/generators.ex
* Move logs to warnings
* Add error for connection pool
> fix: Move logs to warnings; Add error for connection pool

- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20250128220012_realtime_send_sets_topic_config.ex
- mix.exs
Send functions sets topic properly
> fix: Send functions sets topic properly

- mix.exs
- test/integration/rt_channel_test.exs
Ensure token refresh checks write policy
> fix: Ensure token refresh checks write policy

- .github/workflows/tests.yml
- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
> fix: properly handle match error

- lib/realtime/crypto.ex
- lib/realtime/database.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/connect/check_connection.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/plugs/assign_tenant.ex
- mix.exs
- test/realtime/adapters/postgres/protocol_test.exs
- test/realtime/database_test.exs
- test/realtime/repo_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
Reject connections if tenant db has low connections available
> fix: reject connections if tenant db has low connections available

- lib/realtime/application.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/janitor.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/database_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants/janitor_test.exs
ets for janitor instead of syn so we can track users that have disconnected and run cleanup if required.
> fix: use ets for janitor instead of syn

- lib/realtime/rate_counter/rate_counter.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/realtime_channel/broadcast_handler.ex
- test/integration/rt_channel_test.exs
- test/realtime/rate_counter/rate_counter_test.exs
- test/realtime/tenants/replication_connection_test.exs
- test/realtime_web/channels/realtime_channel/broadcast_handler_test.exs
* Skips message counting in case of bad auth
* Simplifies approach and code in both Broadcast Handler and Realtime Channel
* Adds more tests to Broadcast Handler use cases apart from rt_channel integration tests
* Adds RateCounter stop to reduce test flakiness
> fix: Broadcast Handler refactor

- lib/realtime/tenants/janitor.ex
- mix.exs
- test/realtime/tenants/janitor_test.exs
Handle janitor long living connections by tracking not only ETS but also SYN for connections that might be long lived
> fix: Handle janitor long living connections

- lib/realtime/tenants/janitor.ex
- mix.exs
Removing the node from the matching spec which does not have the right value due to being a compile time argument
> fix: janitor not catching some tenants

- lib/realtime/monitoring/prom_ex.ex
- lib/realtime/monitoring/prom_ex/plugins/channels.ex
- lib/realtime/monitoring/prom_ex/plugins/tenants.ex
- lib/realtime/rpc.ex
- lib/realtime_web/channels/realtime_channel/logging.ex
- mix.exs
- test/realtime/database_test.exs
- test/realtime/monitoring/prom_ex_test.exs
- test/realtime/rpc_test.exs
- test/realtime_web/channels/realtime_channel/logging_test.exs
> fix: Improve failure telemetry

- README.md
- lib/realtime/rpc.ex
- lib/realtime/tenants.ex
- lib/realtime/tenants/cache.ex
- lib/realtime/tenants/cache_pub_sub_handler.ex
- lib/realtime/tenants/cache_supervisor.ex
- lib/realtime/tenants/connect.ex
- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/realtime/tenants/cache_supervisor_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants_test.exs
handle suspend properly; handle timeout rpc error
> fix: handle suspend properly; handle timeout rpc error

- config/runtime.exs
- lib/extensions/postgres_cdc_rls/message_dispatcher.ex
- lib/realtime/monitoring/latency.ex
- lib/realtime/rate_counter/rate_counter.ex
- lib/realtime/repo_replica.ex
- lib/realtime/tenants.ex
- lib/realtime/user_counter.ex
- lib/realtime_web/channels/auth/channels_authorization.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/realtime_channel/broadcast_handler.ex
- lib/realtime_web/channels/realtime_channel/logging.ex
- lib/realtime_web/channels/realtime_channel/presence_handler.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/latency_test.exs
- test/realtime/monitoring/latency_test.exs
- test/realtime/monitoring/prom_ex/plugins/tenants_test.exs
- test/realtime/user_counter_test.exs
- test/realtime_web/channels/realtime_channel/logging_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
- test/support/clustered.ex
- test/support/containers.ex
- test/support/generators.ex
- test/test_helper.exs
Add tests to properly capture billable events and when they occur when emulating users use cases
> fix: Test billable events

- .github/workflows/version_updated.yml
Have not tested to make sure this works as expected, especially as
we're upgrading from v41 to v45. Will leave that up to the team.
> fix: remove compromised action

- .github/workflows/tests.yml
- config/test.exs
- coveralls.json
- lib/realtime/database.ex
- lib/realtime/monitoring/prom_ex/plugins/tenant.ex
- lib/realtime/tenants/authorization.ex
- lib/realtime/tenants/batch_broadcast.ex
- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/realtime/database_test.exs
- test/realtime/tenants/authorization_test.exs
- test/realtime_web/channels/realtime_channel/broadcast_handler_test.exs
- test/realtime_web/channels/realtime_channel/presence_handler_test.exs
Exposes two new tenant metrics to measure time til RLS policies are verified during realtime authorization
> fix: expose authorization metrics

- .github/workflows/manual_prod_build.yml
- .github/workflows/prod_build.yml
- .github/workflows/version_updated.yml
- config/runtime.exs
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/user_socket.ex
- mix.exs
- test/realtime/database_test.exs
Bring back setting log level for debugging. We're adding back channel and message level logging so users can see which messages are being sent / received when log_params are set.
> fix: bring back setting log level for debugging

- lib/realtime/tenants/repo/migrations/20240801235015_unlogged_messages_table.ex
- lib/realtime/tenants/repo/migrations/20240805133720_logged_messages_table.ex
- lib/realtime/tenants/repo/migrations/20250107150512_realtime_subscription_unlogged.ex
- lib/realtime/tenants/repo/migrations/20250110162412_realtime_subscription_logged.ex
- mix.exs
oriole compatibility by avoiding LOGGED / UNLOGGED migrations
> fix: oriole compatibility by avoiding LOGGED / UNLOGGED migrations

- lib/realtime/tenants.ex
- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
- priv/repo/seeds.exs
- test/realtime_web/controllers/tenant_controller_test.exs
- test/support/containers.ex
Move migrations to tenant creation instead of healthcheck. Also change seed so we can migrate on startup instead of waiting for self host / cli healthcheck running
> fix: move migration to tenant creation

- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
- test/realtime_web/controllers/tenant_controller_test.exs
Sets the external_id properly based on sub domain.
> fix: properly set the params on creation to be fed by sub domain

- lib/realtime/monitoring/prom_ex/plugins/tenant.ex
- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/database_test.exs
- test/realtime/monitoring/prom_ex/plugins/tenant_test.exs
- test/realtime_web/controllers/tenant_controller_test.exs
- test/support/clustered.ex
- test/support/generators.ex
Handle nil tenant id and test metrics clustered
> fix: handle nil tenant id and test metrics clustered

- lib/realtime/tenants.ex
- mix.exs
- test/realtime_web/controllers/tenant_controller_test.exs
Due to a limitation in the way we create tenants we can't remove the migration code from the healthcheck
> fix: add back migration on healthcheck

- lib/realtime/tenants/connect.ex
- mix.exs
- test/realtime/tenants/connect_test.exs
On ReplicationConnection or Listen module exits we also kill the Connect module to ensure all required elements are properly started up with the next incoming connection from a client.
> fix: On Replication Connection and Listen failure, Connect shuts down

- test/realtime_web/controllers/tenant_controller_test.exs
Fix test expectation to test the correct subject
Testing the wrong subject in a couple of test.
Correct test subject
I also asked Copilot to look at the original test file and it actually found them.
> chore: fix tenant controller tests where 403 is returned

- config/runtime.exs
- lib/realtime_web/channels/user_socket.ex
- mix.exs
- test/realtime/tenants/janitor_test.exs
- test/realtime_web/channels/realtime_channel/broadcast_handler_test.exs
- test/support/containers.ex
- test/support/generators.ex
- test/test_helper.exs
Set correct env var name for `CONNECT_THROTTLE_LIMIT_PER_SECOND`
> fix: Set correct env var name

- Makefile
Add a `help` target to Makefile which automatically uses comments to build the help for each target
I have to read the Makefile to know what it does
Based on the discussion here: https://gist.github.com/prwhite/8168133
> feat: add make help

- .formatter.exs
- .github/workflows/tests.yml
- Makefile
- mix.exs
- priv/repo/dev_seeds.exs
- priv/repo/seeds_before_migration.exs
Extract a new `dev_seeds.exs` file to be used just for development. A following PR will sort out the actual seeds.exs used for self-hosting (cli)
Dev seeds is not working 100% and not rebuilding main and tenant database.
Recreate tenant + tenant db when `make seed`.
Also test dev seeds on CI
> Extract dev seeds from the main seeds file

- lib/realtime/database.ex
- mix.exs
- test/realtime/database_test.exs
Log the amount of required connections so it's clear why Realtime refused to connect.
RealtimeChannel logs the following:
https://github.com/supabase/realtime/blob/1ffc07dd9989e43b69720dbb1b544a9b53662dad/lib/realtime_web/channels/realtime_channel.ex#L135-L137
Maybe the above can be removed given that now we will log at the `Database.check_tenant_connection` level?
```
[error] DatabaseLackOfConnections: Only 91 available connections. At least 126 connections are required.
```
> fix: enhance log lack of connections

- lib/realtime/tenants/connect.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/adapters/postgres/protocol_test.exs
- test/realtime/cluster_strategy/postgres_test.exs
- test/realtime/database_test.exs
- test/realtime/extensions/cdc_rls/subscriptions_checker_test.exs
- test/realtime/extensions/cdc_rls/subscriptions_test.exs
- test/realtime/gen_counter/gen_counter_test.exs
- test/realtime/messages_test.exs
- test/realtime/monitoring/erl_sys_mon_test.exs
- test/realtime/oid_test.exs
- test/realtime/postgres_decoder_test.exs
- test/realtime/tenants/connect/piper_test.exs
- test/realtime/tenants/connect/register_process_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime_web/channels/realtime_channel/presence_handler_test.exs
- test/realtime_web/plugs/auth_tenant_test.exs
- test/realtime_web/views/error_view_test.exs
- test/support/containers.ex
- test/support/containers/container.ex
- test/test_helper.exs
* Run more tests in async mode
* Use less Process.sleep whenever possible
Some time waiting for tests. ~ 300 seconds before my changes
Less time waiting for tests. `Finished in 230.6 seconds (11.5s async, 219.0s sync)` after my changes
Only change I made on lib/* was to help with tests assertion so not really any feature changes
Might have one or two flaky tests but I'm sure I can solve them
> chore: improve test speed

- test/support/containers.ex
- test/test_helper.exs
Ensures that the docker image used for tests is available before starting the tests
It breaks because `docker run` takes more than 10 seconds when downloading an image is included 🐌 . Tests fail waiting etc.
Before:
Now:
> chore: fix container startup for tests

- lib/realtime/tenants/migrations.ex
- lib/realtime/tenants/repo/migrations/20250523164012_run_subscription_index_bridging_disabled.ex
- mix.exs
- test/realtime/messages_test.exs
- test/realtime/repo_test.exs
- test/support/containers.ex
- test/support/containers/container.ex
- test/test_helper.exs
execute migration to set index_bridging to disabled
> fix: execute migration to set index_bridging to disabled

- lib/realtime/monitoring/prom_ex/plugins/phoenix.ex
- mix.exs
It turned out that the opentelemetry setup didn't need the latest ranch
We don't need this change as it's calculating active connections differently
Reverts the change made [here](https://github.com/supabase/realtime/commit/c9683f3f5f94bd2e37494f02c1f4415551e96e5b#diff-9ecf706a524ec8811da1b7cd3c6d8e775f26c9cf39f0abf3b7ccca9a465c0203)
After looking at ranch's code the essential difference is between `all` and `active`:
https://github.com/ninenines/ranch/blob/a692f44567034dacf5efcaa24a24183788594eb7/src/ranch.erl#L354-L355
```
{active_connections, ranch_conns_sup:active_connections(ConnsSup)},
{all_connections, proplists:get_value(active, supervisor:count_children(ConnsSup))},
```
`active` supervisor process is different from what ranch considers an `active` connection.
Active connections …
> fix: revert phoenix promex plugin change

- lib/realtime/monitoring/erl_sys_mon.ex
- mix.exs
- test/realtime/monitoring/erl_sys_mon_test.exs
Fix `ErlSysMon` initialization.
Our application supervision tree adds ErlSysMon like this:
```elixir
[
ErlSysMon,
...
]
```
This translates to `{ErlSysMon, []}` so `ErlSysMon.start_link([])` was being called effectively making system_monitor not track anything. 
I also tested locally calling `:erlang.system_monitor()` which just returns the current configuration. Previously it was returning `:undefined` because nothing was set.
No erlang system monitor messages
System monitor messages are being logged
> fix: ErlSysMon initialization

- lib/extensions/postgres_cdc_rls/replication_poller.ex
- lib/extensions/postgres_cdc_rls/worker_supervisor.ex
- lib/realtime/application.ex
- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/connect/register_process.ex
- mix.exs
- test/e2e/tests.ts
- test/realtime/tenants/connect/register_process_test.exs
- test/realtime/tenants/connect_test.exs
In Connect and PostgresCDC, after syn registration, it also registers into a Registry so we can use it in the Node for easier debugging and support operations
> fix: register locally after syn

- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/replication_connection.ex
- mix.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants/listen_test.exs
- test/realtime/tenants/replication_connection_test.exs
* Fix ReplicationConnection shutdown reason. Any reason that is not `:normal`, `:shutdown` or `{:shutdown, reason}` is considered abnormal. 
* Add more tests to Listen, Connect and ReplicationConnection.
* Simplify Connect shutdown process. There is no need to stop ReplicationConnection and Listen because they monitor the process that started them (Connect). 
One observation that came to mind is that we might as well `Process.link` them if we have them monitoring each other and stopping once the other stops.
> fix: shutdown scenarios for Connect, Listen and ReplicationConnect

- lib/realtime/database.ex
- lib/realtime/monitoring/prom_ex/plugins/tenants.ex
- lib/realtime/rpc.ex
- lib/realtime/tenants/authorization.ex
- lib/realtime/tenants/connect.ex
- mix.exs
- test/realtime/database_test.exs
- test/realtime/monitoring/prom_ex/plugins/tenants_test.exs
- test/realtime/rpc_test.exs
- test/realtime/tenants/authorization_test.exs
- test/realtime/tenants/connect_test.exs
Fix a few places where tenant/external_id/project information was missing on logs and telemetry.
Missing metadata
Metadata is set (when available) on:
* `Rpc.enhanced_call` error log statements
*  `Rpc.enhanced_call` telemetry
* Authorization -> Database.transaction error logs
* Connect error log statements
> Fix missing log and telemetry metadata

- config/test.exs
- lib/realtime/rpc.ex
- lib/realtime/tenants/authorization.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/database_test.exs
- test/realtime/tenants/authorization_remote_test.exs
This way we reduce the amount of information sent between nodes to authorize channels to read and write. 
To authorize RPC calls that were being made through `Database.transaction`.
Now we do the RPC call from a higher level not passing an anonymous function and simplifying the arguments (and consequently the amount of bytes) passed. Roughly 30% smaller using `:erlang.term_to_binary` to calculate (based on our test cases).
Notice that it still calls `Database.transaction` but now it will always be handled locally:
https://github.com/supabase/realtime/blob/488af4e0e04ad7a41aadee7536bd40b47b063c07/lib/realtime/database.ex#L160-L161
> fix: change Authorization policy calls to use RPC when db connection is not local

- lib/realtime/database.ex
- lib/realtime/monitoring/prom_ex/plugins/tenant.ex
- mix.exs
- test/realtime/database_test.exs
- test/realtime/monitoring/prom_ex/plugins/tenant_test.exs
- test/realtime/tenants/authorization_test.exs
Fix read and write authorization check metric collection
```
15:49:18.135 [debug] Measurement not found, expected: count. metric_name:=[:realtime, :tenants, :read_authorization_check]
15:49:18.142 [debug] Measurement not found, expected: count. metric_name:=[:realtime, :tenants, :write_authorization_check]
```
Metrics are exposed through prometheus metrics
> fix: RLS authorization metrics

- lib/realtime/tenants/batch_broadcast.ex
- lib/realtime/tenants/replication_connection.ex
- mix.exs
- test/realtime/tenants/replication_connection_test.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
Change `BatchBroadcast` to use `TenantBroadcaster` and allow `gen_rpc` to be used for broadcast API and `realtime.messages` broadcast.
Also updated the `init_timeout` for `ReplicationConnection` so we don't need to wait 30 seconds during tests 🐌 
It's only using for broadcast coming from RealtimeChannel
Broadcast API and `realtime.messages` broadcast can use `gen_rpc` depending on the `tenant.broadcast_adapter`
Follow-up from https://github.com/supabase/realtime/pull/1425 & https://github.com/supabase/realtime/pull/1419
> fix: use tenant broadcaster everywhere

- lib/realtime_web/tenant_broadcaster/gen_rpc.ex
- mix.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
This ensures that two messages sent to the same topic from the same node are sent one after the other instead of in parallel
GenRpc will pick a random key making it possible that two different messages for the same topic arrive in any order
Ensure that messages sent to the same topic at the same time keep the original order
> fix: change TenantBroadcaster.GenRpc to use topic as a key

- lib/realtime_web/controllers/tenant_controller.ex
- mix.exs
- test/realtime/api_test.exs
- test/realtime_web/controllers/tenant_controller_test.exs
Reload endpoint updated to also shutdown Connect module
> fix: Reload endpoint updated to also shutdown Connect module

- lib/realtime/monitoring/distributed_metrics.ex
- lib/realtime/monitoring/prom_ex.ex
- lib/realtime/monitoring/prom_ex/plugins/distributed.ex
- mix.exs
- test/realtime/monitoring/distributed_metrics_test.exs
- test/realtime/monitoring/prom_ex/plugins/distributed_test.exs
Base on what recon, observer_cli and prometheus.erl fetch
Adds new metrics related to erlang distribution. It gathers basic metrics around the single TCP port that every connected node and node queue size
> feat: add erlang distribution metrics

- lib/realtime/rate_counter/rate_counter.ex
- lib/realtime/tenants/connect/backoff.ex
- lib/realtime/tenants/connect/start_counters.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/plugs/assign_tenant.ex
- mix.exs
- test/realtime/monitoring/distributed_metrics_test.exs
- test/realtime/rate_counter/rate_counter_test.exs
We were leaving them there forever
RateCounters and respective GenCounters are left as active processes forever never shutting them down regardless of activity
Shut them down after 1 hour without any increments.
> fix: set idle_shutdown to all RateCounters to be 1 hour

- lib/realtime/rate_counter/rate_counter.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
- test/support/containers.ex
Fix a couple of flaky tests
I had to change `RateCounter.stop/1` so I had to bump up the version BUT this is only used on tests so not an actual change that impacts real traffic.
> fix: flaky tests

- lib/realtime_web/channels/realtime_channel/logging.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime_web/channels/realtime_channel/logging_test.exs
We might receive non-binary/string messages when logging errors. Let's inspect if not a binary
Fail to log 
```
UnableToSubscribeToPostgres: %Protocol.UndefinedError{
protocol: String.Chars,
value: {:error,...
```
Call `inspect/1` if not a string
Related to https://github.com/supabase/realtime/pull/1445
> fix: RealtimeChannel.Logging when a non binary message is logged

- lib/realtime_web/channels/realtime_channel/logging.ex
- mix.exs
- test/realtime_web/channels/realtime_channel/logging_test.exs
- test/realtime_web/channels/realtime_channel/presence_handler_test.exs
Add metadata to logs by default
> fix: Add metadata to logs by default

- lib/realtime/api.ex
- lib/realtime/tenants.ex
- lib/realtime/tenants/connect.ex
- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/realtime/api_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants_test.exs
- test/support/generators.ex
suspend/unsuspend kills sockets and database connection
> fix: suspend/unsuspend kills sockets and database connection

- lib/realtime_web/channels/auth/jwt_verification.ex
- mix.exs
- test/realtime_web/channels/auth/jwt_verification_test.exs
- test/realtime_web/channels/realtime_channel/broadcast_handler_test.exs
`Joken.Signer.create` does not expect a map for `HS256`
Failing with
```
(Joken.Error) Couldn't recognize the signer algorithm. Possible values are: ["HS256", "HS384", "HS512", "RS256", "RS384", "RS512", "ES256", "ES384", "ES512", "PS256", "PS384", "PS512", "Ed25519", "Ed25519ph", "Ed448", "Ed448ph"]
```
Not failing
> fix: HS256 JWK signature verification

- config/runtime.exs
- lib/realtime/cluster_strategy/postgres.ex
- mix.exs
- test/realtime/cluster_strategy/postgres_test.exs
Pass the same `socket_options` provided to `Realtime.Repo` to the libcluster Postgres strategy
`socket_options` are not sent not allowing IPv6 databases to be used for the libcluster setup
IPv6 databases will work for the cluster strategy as well
> fix: provide socket_options to Postgres libcluster strategy

- lib/realtime/api.ex
- lib/realtime/gen_counter/gen_counter.ex
- lib/realtime/rate_counter/rate_counter.ex
- lib/realtime/tenants.ex
- lib/realtime/tenants/batch_broadcast.ex
- lib/realtime/tenants/connect/start_counters.ex
- lib/realtime_web/channels/realtime_channel.ex
- lib/realtime_web/channels/realtime_channel/broadcast_handler.ex
- lib/realtime_web/channels/realtime_channel/presence_handler.ex
- lib/realtime_web/plugs/assign_tenant.ex
- mix.exs
- test/realtime/gen_counter/gen_counter_test.exs
- test/realtime/monitoring/prom_ex/plugins/tenant_test.exs
- test/realtime/rate_counter/rate_counter_test.exs
- test/realtime/tenants/replication_connection_test.exs
- test/realtime_web/channels/realtime_channel/broadcast_handler_test.exs
- test/realtime_web/channels/realtime_channel/presence_handler_test.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
Allow RateCounter processes to stop when idle for a reasonable amount of time.
`idle_shutdown: :infinity` 🚀 🧑‍🚀 
`RateCounter` processes can safely go away now and get automatically restarted when `RateCounter.get/2` is called and if there is no RateCounter process running.
I also reworked the way that we we were handling the idle timer. Instead of refreshing the idle timer on every `tick` we now let the idle timer message arrive (every 15 minutes) and check if the `bucket` contains only zeros. If that's the case we let it stop. This is so that we don't refresh an idle timer on a busy RateCounter that always has something to account for. It would refresh this timer every second. If they are busy enough the `bucket` won't be full of zeros.
Later on we can probably decrease the idle …
> fix: RateCounter refactor to make idle shutdown safer

- lib/realtime/gen_counter/gen_counter.ex
- mix.exs
- test/realtime/gen_counter/gen_counter_test.exs
We don't need to touch the ETS table if the counter is already 0
It updates the ETS row even when the value is already 0
Avoid the update
> fix: avoid touching the ETS table when counter is 0

- lib/realtime/rate_counter/rate_counter.ex
- lib/realtime/tenants.ex
- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/rate_counter/rate_counter_test.exs
Changes so that RateCounter can detect that a limit has been crossed so that we log once instead of whenever an event (in this case a RealtimeChannel join) happens.
I've also changed to only increment a join when it's not being rate limited. 
We can apply the same solution to other limits we currently have like limit of events, presence events, etc
We log every time a `RealtimeChannel` join has failed due to the rate limit of joins been reached
We log once when the limit it crossed and we won't log again until the average has decreased enough to be below the limit.
> fix: move rate limit message to happen inside the RateCounter

- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/gen_rpc_test.exs
- test/realtime/monitoring/prom_ex/plugins/distributed_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
- test/support/websocket_client.ex
Fix a few issues with Connect & Authorization usage
* Don't reset Authorization policies on `:confirm_token` as the actual token has not changed and only the expiration can be affected here.
* Avoid resetting Authorization policies twice on new "access_token"
* New access token was not being passed to `authorization_context` when a new access token was provided
* Capture Connect RPC errors that were not handled before
Added comments to the code to explain the changes
> fix: realtime channel error cases

- README.md
Add coverage and license badges
> chore: add coverage and license badges to README.md

- lib/realtime_web/channels/realtime_channel.ex
- mix.exs
- test/realtime_web/channels/realtime_channel_test.exs
Rely on `tenant_token` instead of `headers`.  `tenant_token` is assigned by UserSocket based on the `apikey` query string OR the header.
https://github.com/supabase/realtime/blob/5190510ecbf895b5459c67bce126449dafb70900/lib/realtime_web/channels/user_socket.ex#L112-L117
Fixes #1509 
> fix: access token handling

- Dockerfile
- mix.exs
- run.sh
This is anticipated to be a temporary feature that will be deprecated
and removed once we move to a platform that offers easy init container
support.
> feat: add support for generating certs for securing inter-node comms

- lib/realtime/gen_rpc.ex
- mix.exs
- test/realtime/gen_rpc_test.exs
We don't want to try to establish connections to nodes that are not part of `Node.list()`. They most likely went down and will not be communicable. We keep our cluster connected through other means: libcluster.
> fix: Fix GenRpc to not try to connect to nodes that are not alive

- lib/realtime_web/endpoint.ex
- mix.exs
Ddisable UTF8 validation on websocket frames.
Currently all text frames as handled only with JSON which already requires UTF-8
All text frames are validated to be UTF-8 prior to be handled by Phoenix. That's part of the protocol specification.
Skip such validation.
> feat: disable UTF8 validation on websocket frames

- lib/realtime/tenants/connect.ex
- lib/realtime/tenants/replication_connection.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/tenants/connect_test.exs
- test/realtime/tenants/replication_connection_test.exs
- test/support/containers.ex
Verify that replication connection is able to reconnect when faced with WAL bloat issues
> fix: handle wal bloat

- lib/realtime_web/channels/realtime_channel/message_dispatcher.ex
- mix.exs
- test/realtime_web/channels/realtime_channel/message_dispatcher_test.exs
- test/realtime_web/channels/realtime_channel_test.exs
A more defensive approach to fetch the message id from the RealtimeChannel.MessageDispatcher
It's technically possible to send payload that is not a map/object/hash and it could raise at the MessageDispatcher level
It will not raise if the `meta` `id` is not available.
> fix: ensure message id doesn't raise on non-map payloads

- lib/realtime/tenants/connect.ex
- mix.exs
- test/realtime/tenants/connect_test.exs
> fix: match error on Connect

- lib/realtime/monitoring/erl_sys_mon.ex
- mix.exs
- test/realtime/monitoring/erl_sys_mon_test.exs
Include `initial_call`, `ancestors`, `registered_name`, `message_queue_len` and `total_heap_size`
Also bump `long_schedule` and `long_gc`
> fix: improve ErlSysMon logging for processes

- config/runtime.exs
- lib/realtime/gen_rpc/pub_sub.ex
- mix.exs
- test/realtime/gen_rpc_pub_sub_test.exs
The GenRpcPubSub workers receive tons of messages. Changing the message queue to be off-heap will help us not reach high max heap size limits and faster GC on this process.
This is also how the `gen_rpc` processes work: https://github.com/supabase/gen_rpc/blob/901aada9adb307ff89a8be197a5d384e69dd57d6/src/gen_rpc_helper.erl#L110
> Memory allocation makes such “off-heap” messages slightly more expensive but they’re very neat for processes that receive a ton of messages. We don’t need to interact with the receiver when copying the message – only when adding it to the queue – and since the only way a process can see a message is by matching them in a receive expression, the GC doesn’t need to consider unmatched messages which further reduces latency. …
> fix: move message queue data to off-heap for gen_rpc pub sub workers

- lib/realtime/tenants.ex
- lib/realtime/tenants/connect.ex
- mix.exs
- test/realtime/tenants/connect_test.exs
- test/realtime_web/controllers/broadcast_controller_test.exs
We should only increment when there is an error connecting. 
I've renamed the rate counter to explicitly say that it's just for connection errors.
> fix: rate limit Connect.lookup_or_start_connection on error only

- lib/realtime_web/channels/realtime_channel/presence_handler.ex
- mix.exs
> fix: hardcode presence limit

- lib/realtime/gen_rpc/pub_sub.ex
- lib/realtime_web/channels/realtime_channel/presence_handler.ex
- lib/realtime_web/channels/tenant_rate_limiters.ex
- lib/realtime_web/channels/user_socket.ex
- lib/realtime_web/endpoint.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/gen_rpc_pub_sub_test.exs
- test/realtime_web/channels/realtime_channel/presence_handler_test.exs
- test/realtime_web/channels/tenant_rate_limiters_test.exs
move connect rate limit to socket
> fix: move connect rate limit to socket

- .github/workflows/tests.yml
- lib/extensions/postgres_cdc_rls/replication_poller.ex
- lib/realtime/tenants.ex
- mix.exs
- test/integration/rt_channel_test.exs
- test/realtime/extensions/cdc_rls/cdc_rls_test.exs
Fix ReplicationPoller to rate limit db events.
Unlimited
Limited
> fix: limit db events
